# SoftRelTools GNUmakefile for KinematicFitter test
################################################################

# Build executables
BINS =
# Build test executables
TBINS = testKinematicFitter

skip_files := 

override LINK_KinematicFitter += KinematicFitter

################################################################
include PackageList/link_all.mk
include SoftRelTools/standard.mk
include SoftRelTools/binclean.mk
include SoftRelTools/arch_spec_root.mk
