//
// File generated by /home/cdfsoft/products/root/v4_00_08gGCC_3_4_3/Linux+2.4/bin/rootcint at Mon Jul 24 13:28:46 2006.
// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

#include "dict_KinematicFitter.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TStreamerInfo.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;

#include "RtypesImp.h"

#include "TVectorProxy.h"

namespace ROOT {
   namespace Shadow {
   } // Of namespace ROOT::Shadow
} // Of namespace ROOT

namespace ROOT {
   void KinematicFitter_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void KinematicFitter_Dictionary();
   static TClass *KinematicFitter_IsA(const void*);
   static void *new_KinematicFitter(void *p = 0);
   static void *newArray_KinematicFitter(Long_t size);
   static void delete_KinematicFitter(void *p);
   static void deleteArray_KinematicFitter(void *p);
   static void destruct_KinematicFitter(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const KinematicFitter*)
   {
      KinematicFitter *ptr = 0;
      static ROOT::TGenericClassInfo 
         instance("KinematicFitter", "include/KinematicFitter.h", 16,
                  typeid(KinematicFitter), DefineBehavior(ptr, ptr),
                  0, &KinematicFitter_Dictionary, &KinematicFitter_IsA, 0,
                  sizeof(KinematicFitter) );
      instance.SetNew(&new_KinematicFitter);
      instance.SetNewArray(&newArray_KinematicFitter);
      instance.SetDelete(&delete_KinematicFitter);
      instance.SetDeleteArray(&deleteArray_KinematicFitter);
      instance.SetDestructor(&destruct_KinematicFitter);
      return &instance;
   }
   // Static variable to force the class initialization
   static ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const KinematicFitter*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void KinematicFitter_Dictionary() {
      ROOT::GenerateInitInstance((const KinematicFitter*)0x0)->GetClass();
   }

}

namespace ROOT {
   // Return the actual TClass for the object argument
   static TClass *KinematicFitter_IsA(const void *obj) {
      return GetROOT()->GetClass(typeid(*(::KinematicFitter*)obj));
   }
   // Wrappers around operator new
   static void *new_KinematicFitter(void *p) {
      return  p ? ::new((ROOT::TOperatorNewHelper*)p) ::KinematicFitter : new ::KinematicFitter;
   }
   static void *newArray_KinematicFitter(Long_t size) {
      return new ::KinematicFitter[size];
   }
   // Wrapper around operator delete
   static void delete_KinematicFitter(void *p) {
      delete ((::KinematicFitter*)p);
   }
   static void deleteArray_KinematicFitter(void *p) {
      delete [] ((::KinematicFitter*)p);
   }
   static void destruct_KinematicFitter(void *p) {
      typedef ::KinematicFitter current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::KinematicFitter

/********************************************************
* objects/dict_KinematicFitter.C
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtabledict_KinematicFitter();

extern "C" void G__set_cpp_environmentdict_KinematicFitter() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("KinematicFitter.h");
  G__cpp_reset_tagtabledict_KinematicFitter();
}
class G__objectsdIdict_KinematicFitterdOC_tag {};

void* operator new(size_t size,G__objectsdIdict_KinematicFitterdOC_tag* p) {
  if(p && G__PVOID!=G__getgvp()) return((void*)p);
#ifndef G__ROOT
  return(malloc(size));
#else
  return(::operator new(size));
#endif
}

/* dummy, for exception */
#ifdef G__EH_DUMMY_DELETE
void operator delete(void *p,G__objectsdIdict_KinematicFitterdOC_tag* x) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}
#endif

static void G__operator_delete(void *p) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}

void G__DELDMY_objectsdIdict_KinematicFitterdOC() { G__operator_delete(0); }

extern "C" int G__cpp_dllrevdict_KinematicFitter() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* KinematicFitter */
static int G__dict_KinematicFitter_559_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   KinematicFitter *p=NULL;
   if(G__getaryconstruct()) p=new KinematicFitter[G__getaryconstruct()];
   else p=::new((G__objectsdIdict_KinematicFitterdOC_tag*)G__getgvp()) KinematicFitter;
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->numInputParticles());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_3_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->numVirtualParticles());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->setNumIterations((int)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->setChi2Delta((double)G__double(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->setMaxChi2((double)G__double(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->setCovarianceMode((KinematicFitter::CovarianceMode)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->clearAllInputParticles();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->addInputParticle(*(TLorentzVector*)libp->para[0].ref,*(TMatrixD*)libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 4:
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->addInputParticle(*(TLorentzVector*)libp->para[0].ref,(double)G__double(libp->para[1])
,(double)G__double(libp->para[2]),(double)G__double(libp->para[3])));
      break;
   case 3:
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->addInputParticle(*(TLorentzVector*)libp->para[0].ref,(double)G__double(libp->para[1])
,(double)G__double(libp->para[2])));
      break;
   case 2:
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->addInputParticle(*(TLorentzVector*)libp->para[0].ref,(double)G__double(libp->para[1])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->addInputParticle(*(TLorentzVector*)libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_2_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->updateErrorForInputParticle((int)G__int(libp->para[0]),(double)G__double(libp->para[1])
,(double)G__double(libp->para[2]),(double)G__double(libp->para[3]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_3_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 6:
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->createVirtualParticle((int)G__int(libp->para[0]),(int)G__int(libp->para[1])
,(int)G__int(libp->para[2]),(int)G__int(libp->para[3])
,(int)G__int(libp->para[4]),(int)G__int(libp->para[5])));
      break;
   case 5:
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->createVirtualParticle((int)G__int(libp->para[0]),(int)G__int(libp->para[1])
,(int)G__int(libp->para[2]),(int)G__int(libp->para[3])
,(int)G__int(libp->para[4])));
      break;
   case 4:
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->createVirtualParticle((int)G__int(libp->para[0]),(int)G__int(libp->para[1])
,(int)G__int(libp->para[2]),(int)G__int(libp->para[3])));
      break;
   case 3:
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->createVirtualParticle((int)G__int(libp->para[0]),(int)G__int(libp->para[1])
,(int)G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->createVirtualParticle((int)G__int(libp->para[0]),(int)G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->createVirtualParticle((int)G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->createVirtualParticle());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_4_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->createVirtualParticle(*(KinematicFitter::IVec*)libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_5_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 7:
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->updateVirtualParticle(
(int)G__int(libp->para[0]),(int)G__int(libp->para[1])
,(int)G__int(libp->para[2]),(int)G__int(libp->para[3])
,(int)G__int(libp->para[4]),(int)G__int(libp->para[5])
,(int)G__int(libp->para[6]));
      break;
   case 6:
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->updateVirtualParticle((int)G__int(libp->para[0]),(int)G__int(libp->para[1])
,(int)G__int(libp->para[2]),(int)G__int(libp->para[3])
,(int)G__int(libp->para[4]),(int)G__int(libp->para[5]));
      break;
   case 5:
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->updateVirtualParticle((int)G__int(libp->para[0]),(int)G__int(libp->para[1])
,(int)G__int(libp->para[2]),(int)G__int(libp->para[3])
,(int)G__int(libp->para[4]));
      break;
   case 4:
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->updateVirtualParticle((int)G__int(libp->para[0]),(int)G__int(libp->para[1])
,(int)G__int(libp->para[2]),(int)G__int(libp->para[3]));
      break;
   case 3:
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->updateVirtualParticle((int)G__int(libp->para[0]),(int)G__int(libp->para[1])
,(int)G__int(libp->para[2]));
      break;
   case 2:
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->updateVirtualParticle((int)G__int(libp->para[0]),(int)G__int(libp->para[1]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_6_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->updateVirtualParticle((int)G__int(libp->para[0]),*(KinematicFitter::IVec*)libp->para[1].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_7_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 6:
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->createSuperVirtualParticle((int)G__int(libp->para[0]),(int)G__int(libp->para[1])
,(int)G__int(libp->para[2]),(int)G__int(libp->para[3])
,(int)G__int(libp->para[4]),(int)G__int(libp->para[5])));
      break;
   case 5:
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->createSuperVirtualParticle((int)G__int(libp->para[0]),(int)G__int(libp->para[1])
,(int)G__int(libp->para[2]),(int)G__int(libp->para[3])
,(int)G__int(libp->para[4])));
      break;
   case 4:
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->createSuperVirtualParticle((int)G__int(libp->para[0]),(int)G__int(libp->para[1])
,(int)G__int(libp->para[2]),(int)G__int(libp->para[3])));
      break;
   case 3:
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->createSuperVirtualParticle((int)G__int(libp->para[0]),(int)G__int(libp->para[1])
,(int)G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->createSuperVirtualParticle((int)G__int(libp->para[0]),(int)G__int(libp->para[1])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_8_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->createSuperVirtualParticle(*(KinematicFitter::IVec*)libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->addSingleMassConstraint((int)G__int(libp->para[0]),(double)G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_0_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->addEqualMassConstraint((int)G__int(libp->para[0]),(int)G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_1_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->updateSingleMassConstraint((int)G__int(libp->para[0]),(double)G__double(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_2_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letdouble(result7,100,(double)((KinematicFitter*)(G__getstructoffset()))->currentSingleMassConstraint((int)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_3_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->setConstraintActive((int)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_4_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->setConstraintInactive((int)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_5_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,103,(long)((KinematicFitter*)(G__getstructoffset()))->isConstraintActive((int)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_6_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->saveCurrentConstraintsAsDefault();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_7_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->resetConstraints();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_8_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->numConstraints());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_9_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((KinematicFitter*)(G__getstructoffset()))->numTotalConstraints());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_0_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
      {
        TLorentzVector *pobj,xobj=((KinematicFitter*)(G__getstructoffset()))->particleMom((int)G__int(libp->para[0]),(KinematicFitter::InOutType)G__int(libp->para[1]));
        pobj=new TLorentzVector(xobj);
        result7->obj.i=(long)((void*)pobj); result7->ref=result7->obj.i;
        G__store_tempobject(*result7);
      }
      break;
   case 1:
      {
        TLorentzVector *pobj,xobj=((KinematicFitter*)(G__getstructoffset()))->particleMom((int)G__int(libp->para[0]));
        pobj=new TLorentzVector(xobj);
        result7->obj.i=(long)((void*)pobj); result7->ref=result7->obj.i;
        G__store_tempobject(*result7);
      }
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_1_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
      G__letdouble(result7,100,(double)((KinematicFitter*)(G__getstructoffset()))->E((int)G__int(libp->para[0]),(KinematicFitter::InOutType)G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7,100,(double)((KinematicFitter*)(G__getstructoffset()))->E((int)G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_2_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
      G__letdouble(result7,100,(double)((KinematicFitter*)(G__getstructoffset()))->Px((int)G__int(libp->para[0]),(KinematicFitter::InOutType)G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7,100,(double)((KinematicFitter*)(G__getstructoffset()))->Px((int)G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_3_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
      G__letdouble(result7,100,(double)((KinematicFitter*)(G__getstructoffset()))->Py((int)G__int(libp->para[0]),(KinematicFitter::InOutType)G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7,100,(double)((KinematicFitter*)(G__getstructoffset()))->Py((int)G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_4_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
      G__letdouble(result7,100,(double)((KinematicFitter*)(G__getstructoffset()))->Pz((int)G__int(libp->para[0]),(KinematicFitter::InOutType)G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7,100,(double)((KinematicFitter*)(G__getstructoffset()))->Pz((int)G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_5_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
      {
        TLorentzVector *pobj,xobj=((KinematicFitter*)(G__getstructoffset()))->virtualParticleMom((int)G__int(libp->para[0]),(KinematicFitter::InOutType)G__int(libp->para[1]));
        pobj=new TLorentzVector(xobj);
        result7->obj.i=(long)((void*)pobj); result7->ref=result7->obj.i;
        G__store_tempobject(*result7);
      }
      break;
   case 1:
      {
        TLorentzVector *pobj,xobj=((KinematicFitter*)(G__getstructoffset()))->virtualParticleMom((int)G__int(libp->para[0]));
        pobj=new TLorentzVector(xobj);
        result7->obj.i=(long)((void*)pobj); result7->ref=result7->obj.i;
        G__store_tempobject(*result7);
      }
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_6_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->fillAllInputMomentumVector(*(KinematicFitter::FourVectorVec*)libp->para[0].ref,(KinematicFitter::InOutType)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->fillAllInputMomentumVector(*(KinematicFitter::FourVectorVec*)libp->para[0].ref);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_7_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->fillAllVirtualMomentumVector(*(KinematicFitter::FourVectorVec*)libp->para[0].ref,(KinematicFitter::InOutType)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((KinematicFitter*)(G__getstructoffset()))->fillAllVirtualMomentumVector(*(KinematicFitter::FourVectorVec*)libp->para[0].ref);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_KinematicFitter_559_8_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letdouble(result7,100,(double)((KinematicFitter*)(G__getstructoffset()))->minimizeChi2());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__dict_KinematicFitter_559_5_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash)
{
   KinematicFitter *p;
   void *xtmp = (void*)G__int(libp->para[0]);
   p=new KinematicFitter(*(KinematicFitter*)xtmp);
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef KinematicFitter G__TKinematicFitter;
static int G__dict_KinematicFitter_559_6_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(0==G__getstructoffset()) return(1);
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (KinematicFitter *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         ((KinematicFitter *)((G__getstructoffset())+sizeof(KinematicFitter)*i))->~G__TKinematicFitter();
   else {
     long G__Xtmp=G__getgvp();
     G__setgvp(G__PVOID);
     ((KinematicFitter *)(G__getstructoffset()))->~G__TKinematicFitter();
     G__setgvp(G__Xtmp);
     G__operator_delete((void*)G__getstructoffset());
   }
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__dict_KinematicFitter_559_7_6(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   KinematicFitter *dest = (KinematicFitter*)(G__getstructoffset());
   *dest = (*(KinematicFitter*)libp->para[0].ref);
   const KinematicFitter& obj = *dest;
   result7->ref=(long)(&obj); result7->obj.i=(long)(&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* KinematicFitter */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncdict_KinematicFitter {
 public:
  G__Sizep2memfuncdict_KinematicFitter() {p=&G__Sizep2memfuncdict_KinematicFitter::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncdict_KinematicFitter::*p)();
};

size_t G__get_sizep2memfuncdict_KinematicFitter()
{
  G__Sizep2memfuncdict_KinematicFitter a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancedict_KinematicFitter() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetabledict_KinematicFitter() {

   /* Setting up typedef entry */
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("vector<unsigned int>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("vector<TLorentzVector>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("FourVectorVec",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("IVec",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEintcOallocatorlEintgRsPgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<IVec>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("vector<vector<int,allocator<int> >>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("IVecVec",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TMatrixD>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETMatrixDcOallocatorlETMatrixDgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETMatrixDcOallocatorlETMatrixDgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETMatrixDcOallocatorlETMatrixDgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETMatrixDcOallocatorlETMatrixDgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETMatrixDcOallocatorlETMatrixDgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("TMatrixDVec",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETMatrixDcOallocatorlETMatrixDgRsPgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TMatrixD*>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETMatrixDmUcOallocatorlETMatrixDmUgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETMatrixDmUcOallocatorlETMatrixDmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETMatrixDmUcOallocatorlETMatrixDmUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETMatrixDmUcOallocatorlETMatrixDmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETMatrixDmUcOallocatorlETMatrixDmUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("TMatrixDPtrVec",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETMatrixDmUcOallocatorlETMatrixDmUgRsPgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("IIMap",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ISet",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ConstraintStruct>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLConstraintStructcOallocatorlEKinematicFittercLcLConstraintStructgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEKinematicFittercLcLConstraintStructcOallocatorlEKinematicFittercLcLConstraintStructgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLConstraintStructcOallocatorlEKinematicFittercLcLConstraintStructgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEKinematicFittercLcLConstraintStructcOallocatorlEKinematicFittercLcLConstraintStructgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLConstraintStructcOallocatorlEKinematicFittercLcLConstraintStructgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("vector<KinematicFitter::ConstraintStruct>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLConstraintStructcOallocatorlEKinematicFittercLcLConstraintStructgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("ConstraintVec",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLConstraintStructcOallocatorlEKinematicFittercLcLConstraintStructgRsPgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<VirtualParticle>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLVirtualParticlecOallocatorlEKinematicFittercLcLVirtualParticlegRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEKinematicFittercLcLVirtualParticlecOallocatorlEKinematicFittercLcLVirtualParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLVirtualParticlecOallocatorlEKinematicFittercLcLVirtualParticlegRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEKinematicFittercLcLVirtualParticlecOallocatorlEKinematicFittercLcLVirtualParticlegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLVirtualParticlecOallocatorlEKinematicFittercLcLVirtualParticlegRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("vector<KinematicFitter::VirtualParticle>",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLVirtualParticlecOallocatorlEKinematicFittercLcLVirtualParticlegRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: dict_KinematicFitter.C,v 1.1 2006/07/24 19:39:27 boveia Exp $",0);
   G__search_typename2("VirtualParticleVec",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLVirtualParticlecOallocatorlEKinematicFittercLcLVirtualParticlegRsPgR),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("IVecIter",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEintcOallocatorlEintgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("IVecVecIter",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("IIMapIter",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ISetIter",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ConstraintVecIter",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLConstraintStructcOallocatorlEKinematicFittercLcLConstraintStructgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("VirtualParticleVecIter",117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLVirtualParticlecOallocatorlEKinematicFittercLcLVirtualParticlegRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* KinematicFitter */
static void G__setup_memvarKinematicFitter(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter));
   { KinematicFitter *p; p=(KinematicFitter*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFittercLcLdA),-1,-2,1,"kEnergy=0",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFittercLcLdA),-1,-2,1,"kPx=1",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFittercLcLdA),-1,-2,1,"kPy=2",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFittercLcLdA),-1,-2,1,"kPz=3",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFittercLcLdA),-1,-2,1,"kNumParametersPerParticle=4",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFittercLcLInOutType),-1,-2,1,"kOriginal=0",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFittercLcLInOutType),-1,-2,1,"kIntermediate=1",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFittercLcLInOutType),-1,-2,1,"kModified=2",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFittercLcLConstraintType),-1,-2,1,"kSingleMassConstraint=0",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFittercLcLConstraintType),-1,-2,1,"kEqualMassConstraint=1",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFittercLcLCovarianceMode),-1,-2,1,"kNormalCovarMode=0",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFittercLcLCovarianceMode),-1,-2,1,"kFastCovarMode=1",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFittercLcLCovarianceMode),-1,-2,1,"kKeepCovarMode=2",0,(char*)NULL);
   G__memvar_setup((void*)NULL,117,0,0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR),G__defined_typename("FourVectorVec"),-1,4,"m_inputParticles=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,117,0,0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR),G__defined_typename("FourVectorVec"),-1,4,"m_middleParticles=",0,"intermediate step");
   G__memvar_setup((void*)NULL,117,0,0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR),G__defined_typename("FourVectorVec"),-1,4,"m_outputParticles=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,117,0,0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETMatrixDcOallocatorlETMatrixDgRsPgR),G__defined_typename("TMatrixDVec"),-1,4,"m_inputErrorMatricies=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,117,0,0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLVirtualParticlecOallocatorlEKinematicFittercLcLVirtualParticlegRsPgR),G__defined_typename("VirtualParticleVec"),-1,4,"m_virtualParticles=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,117,0,0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLConstraintStructcOallocatorlEKinematicFittercLcLConstraintStructgRsPgR),G__defined_typename("ConstraintVec"),-1,4,"m_constraintVec=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,100,0,0,-1,-1,-1,4,"m_chi2delta=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,100,0,0,-1,-1,-1,4,"m_maxChi2=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,-1,-1,4,"m_numIterations=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFittercLcLCovarianceMode),-1,-1,4,"m_covarMode=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,117,0,0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR),G__defined_typename("ISet"),-1,4,"m_usedInputPartSet=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,117,0,0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgR),G__defined_typename("IIMap"),-1,4,"m_usedInputPartMap=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_TMatrixD),-1,-1,4,"m_V_a0=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,117,0,0,G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETMatrixDmUcOallocatorlETMatrixDmUgRsPgR),G__defined_typename("TMatrixDPtrVec"),-2,4,"sm_matrixPtrVec=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvardict_KinematicFitter() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncKinematicFitter(void) {
   /* KinematicFitter */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter));
   G__memfunc_setup("KinematicFitter",1539,G__dict_KinematicFitter_559_1_0,105,G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("numInputParticles",1799,G__dict_KinematicFitter_559_2_0,105,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("numVirtualParticles",2014,G__dict_KinematicFitter_559_3_0,105,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setNumIterations",1694,G__dict_KinematicFitter_559_4_0,121,-1,-1,0,1,1,1,0,"i - - 0 - num",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setChi2Delta",1148,G__dict_KinematicFitter_559_5_0,121,-1,-1,0,1,1,1,0,"d - - 0 - delta",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setMaxChi2",952,G__dict_KinematicFitter_559_6_0,121,-1,-1,0,1,1,1,0,"d - - 0 - max",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setCovarianceMode",1740,G__dict_KinematicFitter_559_7_0,121,-1,-1,0,1,1,1,0,"i 'KinematicFitter::CovarianceMode' - 0 - mode",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("clearAllInputParticles",2263,G__dict_KinematicFitter_559_8_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("addInputParticle",1645,G__dict_KinematicFitter_559_9_0,105,-1,-1,0,2,1,1,0,
"u 'TLorentzVector' - 11 - vec u 'TMatrixD' - 11 - errMat",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("addInputParticle",1645,G__dict_KinematicFitter_559_0_1,105,-1,-1,0,4,1,1,0,
"u 'TLorentzVector' - 11 - vec d - - 0 - dE "
"d - - 0 0. dTheta d - - 0 0. dPhi",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("addInputParticle",1645,G__dict_KinematicFitter_559_1_1,105,-1,-1,0,1,1,1,0,"u 'TLorentzVector' - 11 - vec",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("updateErrorForInputParticle",2808,G__dict_KinematicFitter_559_2_1,121,-1,-1,0,4,1,1,0,
"i - - 0 - index d - - 0 - dE "
"d - - 0 - dPhi d - - 0 - dTheta",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("createVirtualParticle",2191,G__dict_KinematicFitter_559_3_1,105,-1,-1,0,6,1,1,0,
"i - - 0 -1 in1 i - - 0 -1 in2 "
"i - - 0 -1 in3 i - - 0 -1 in4 "
"i - - 0 -1 in5 i - - 0 -1 in6",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("createVirtualParticle",2191,G__dict_KinematicFitter_559_4_1,105,-1,-1,0,1,1,1,0,"u 'vector<int,allocator<int> >' 'KinematicFitter::IVec' 1 - vec",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("updateVirtualParticle",2206,G__dict_KinematicFitter_559_5_1,121,-1,-1,0,7,1,1,0,
"i - - 0 - virtualIndex i - - 0 - in1 "
"i - - 0 -1 in2 i - - 0 -1 in3 "
"i - - 0 -1 in4 i - - 0 -1 in5 "
"i - - 0 -1 in6",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("updateVirtualParticle",2206,G__dict_KinematicFitter_559_6_1,121,-1,-1,0,2,1,1,0,
"i - - 0 - virtualIndex u 'vector<int,allocator<int> >' 'KinematicFitter::IVec' 1 - vec",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("createSuperVirtualParticle",2718,G__dict_KinematicFitter_559_7_1,105,-1,-1,0,6,1,1,0,
"i - - 0 - in1 i - - 0 - in2 "
"i - - 0 -1 in3 i - - 0 -4 in4 "
"i - - 0 -1 in5 i - - 0 -1 in6",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("createSuperVirtualParticle",2718,G__dict_KinematicFitter_559_8_1,105,-1,-1,0,1,1,1,0,"u 'vector<int,allocator<int> >' 'KinematicFitter::IVec' 1 - vec",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("addSingleMassConstraint",2372,G__dict_KinematicFitter_559_9_1,105,-1,-1,0,2,1,1,0,
"i - - 0 - virtIndex d - - 0 - mass",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("addEqualMassConstraint",2266,G__dict_KinematicFitter_559_0_2,105,-1,-1,0,2,1,1,0,
"i - - 0 - virtIndex1 i - - 0 - virtIndex2",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("updateSingleMassConstraint",2718,G__dict_KinematicFitter_559_1_2,121,-1,-1,0,2,1,1,0,
"i - - 0 - constraintIndex d - - 0 - mass",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("currentSingleMassConstraint",2846,G__dict_KinematicFitter_559_2_2,100,-1,-1,0,1,1,1,0,"i - - 0 - constraintIndex",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setConstraintActive",1997,G__dict_KinematicFitter_559_3_2,121,-1,-1,0,1,1,1,0,"i - - 0 - constraintIndex",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setConstraintInactive",2212,G__dict_KinematicFitter_559_4_2,121,-1,-1,0,1,1,1,0,"i - - 0 - constraintIndex",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("isConstraintActive",1885,G__dict_KinematicFitter_559_5_2,103,-1,-1,0,1,1,1,0,"i - - 0 - constraintIndex",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("saveCurrentConstraintsAsDefault",3235,G__dict_KinematicFitter_559_6_2,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("resetConstraints",1723,G__dict_KinematicFitter_559_7_2,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("numConstraints",1512,G__dict_KinematicFitter_559_8_2,105,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("numTotalConstraints",2028,G__dict_KinematicFitter_559_9_2,105,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("particleMom",1149,G__dict_KinematicFitter_559_0_3,117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_TLorentzVector),-1,0,2,1,1,0,
"i - - 0 - index i 'KinematicFitter::InOutType' - 0 kModified type",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("E",69,G__dict_KinematicFitter_559_1_3,100,-1,-1,0,2,1,1,0,
"i - - 0 - index i 'KinematicFitter::InOutType' - 0 kModified type",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Px",200,G__dict_KinematicFitter_559_2_3,100,-1,-1,0,2,1,1,0,
"i - - 0 - index i 'KinematicFitter::InOutType' - 0 kModified type",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Py",201,G__dict_KinematicFitter_559_3_3,100,-1,-1,0,2,1,1,0,
"i - - 0 - index i 'KinematicFitter::InOutType' - 0 kModified type",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Pz",202,G__dict_KinematicFitter_559_4_3,100,-1,-1,0,2,1,1,0,
"i - - 0 - index i 'KinematicFitter::InOutType' - 0 kModified type",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("virtualParticleMom",1892,G__dict_KinematicFitter_559_5_3,117,G__get_linked_tagnum(&G__dict_KinematicFitterLN_TLorentzVector),-1,0,2,1,1,0,
"i - - 0 - index i 'KinematicFitter::InOutType' - 0 kModified type",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("fillAllInputMomentumVector",2709,G__dict_KinematicFitter_559_6_3,121,-1,-1,0,2,1,1,0,
"u 'vector<TLorentzVector,allocator<TLorentzVector> >' 'KinematicFitter::FourVectorVec' 1 - retval i 'KinematicFitter::InOutType' - 0 kModified type",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("fillAllVirtualMomentumVector",2924,G__dict_KinematicFitter_559_7_3,121,-1,-1,0,2,1,1,0,
"u 'vector<TLorentzVector,allocator<TLorentzVector> >' 'KinematicFitter::FourVectorVec' 1 - retval i 'KinematicFitter::InOutType' - 0 kModified type",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("minimizeChi2",1192,G__dict_KinematicFitter_559_8_3,100,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_validateInputIndex",1969,(G__InterfaceMethod)NULL,103,-1,-1,0,4,1,4,0,
"u 'string' - 0 - filename i - - 0 - linenum "
"i 'KinematicFitter::InOutType' - 0 - type i - - 0 - index",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_validateVirtualPartIndex",2591,(G__InterfaceMethod)NULL,103,-1,-1,0,5,1,4,0,
"u 'string' - 0 - filename i - - 0 - linenum "
"i 'KinematicFitter::InOutType' - 0 - type i - - 0 - index "
"g - - 0 false checkInputParticles",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_validateConstraintIndex",2502,(G__InterfaceMethod)NULL,103,-1,-1,0,3,1,4,0,
"u 'string' - 0 - filename i - - 0 - linenum "
"i - - 0 - index",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_setupSingleConstraint",2327,(G__InterfaceMethod)NULL,121,-1,-1,0,4,1,4,0,
"U 'TMatrixD' - 0 - D U 'TMatrixD' - 0 - dvec "
"i - - 1 - constraintIndex u 'KinematicFitter::ConstraintStruct' - 11 - constraint",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_setupEqualConstraint",2221,(G__InterfaceMethod)NULL,121,-1,-1,0,4,1,4,0,
"U 'TMatrixD' - 0 - D U 'TMatrixD' - 0 - dvec "
"i - - 1 - constraintIndex u 'KinematicFitter::ConstraintStruct' - 11 - constraint",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_deltaAlpha",1103,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__dict_KinematicFitterLN_TMatrixD),-1,0,2,1,4,0,
"i - - 0 - numUsedParticles g - - 0 true useDeleteList",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_allInputParticles",1871,(G__InterfaceMethod)NULL,121,-1,-1,0,3,1,4,0,
"i - - 0 - virtualParticleIndex u 'vector<int,allocator<int> >' 'KinematicFitter::IVec' 1 - retval "
"g - - 0 true clear",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_calcOffset",1113,(G__InterfaceMethod)NULL,105,-1,-1,0,1,1,4,0,"i - - 0 - partIndex",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_numUsedInputParticles",2295,(G__InterfaceMethod)NULL,105,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_zeroMatrix",1172,(G__InterfaceMethod)NULL,121,-1,-1,0,1,3,4,0,"u 'TMatrixD' - 1 - matrix",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_zeroMatrix",1172,(G__InterfaceMethod)NULL,121,-1,-1,0,1,3,4,0,"U 'TMatrixD' - 0 - matrix",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_covarianceMatrixFromDeltaETP",2902,(G__InterfaceMethod)NULL,121,-1,-1,0,5,3,4,0,
"u 'TMatrixD' - 1 - matrix u 'TLorentzVector' - 11 - vec "
"d - - 0 - dE d - - 0 - dTheta "
"d - - 0 - dPhi",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_covarianceMatrixALaMarcel",2609,(G__InterfaceMethod)NULL,121,-1,-1,0,3,3,4,0,
"u 'TMatrixD' - 1 - matrix u 'TLorentzVector' - 11 - vec "
"d - - 0 0.15 percent",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_insertSmallMatrixIntoLarge",2791,(G__InterfaceMethod)NULL,121,-1,-1,0,4,3,4,0,
"u 'TMatrixD' - 11 - small u 'TMatrixD' - 1 - large "
"i - - 0 - rowOff i - - 0 - colOff",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_mult",545,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__dict_KinematicFitterLN_TMatrixD),-1,0,3,3,4,0,
"u 'TMatrixD' - 11 - alpha u 'TMatrixD' - 11 - beta "
"g - - 0 true useDeleteList",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_mult",545,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__dict_KinematicFitterLN_TMatrixD),-1,0,3,3,4,0,
"U 'TMatrixD' - 0 - alphaPtr U 'TMatrixD' - 0 - betaPtr "
"g - - 0 true useDeleteList",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_mult",545,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__dict_KinematicFitterLN_TMatrixD),-1,0,4,3,4,0,
"u 'TMatrixD' - 11 - alpha u 'TMatrixD' - 11 - beta "
"u 'TMatrixD' - 11 - gamma g - - 0 true useDeleteList",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_mult",545,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__dict_KinematicFitterLN_TMatrixD),-1,0,4,3,4,0,
"U 'TMatrixD' - 0 - alphaPtr U 'TMatrixD' - 0 - betaPtr "
"U 'TMatrixD' - 0 - gammaPtr g - - 0 true useDeleteList",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_add",392,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__dict_KinematicFitterLN_TMatrixD),-1,0,3,3,4,0,
"u 'TMatrixD' - 11 - alpha u 'TMatrixD' - 11 - beta "
"g - - 0 true useDeleteList",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_add",392,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__dict_KinematicFitterLN_TMatrixD),-1,0,3,3,4,0,
"U 'TMatrixD' - 0 - alphaPtr U 'TMatrixD' - 0 - betaPtr "
"g - - 0 true useDeleteList",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_subtract",967,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__dict_KinematicFitterLN_TMatrixD),-1,0,3,3,4,0,
"u 'TMatrixD' - 11 - alpha u 'TMatrixD' - 11 - beta "
"g - - 0 true useDeleteList",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_subtract",967,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__dict_KinematicFitterLN_TMatrixD),-1,0,3,3,4,0,
"U 'TMatrixD' - 0 - alphaPtr U 'TMatrixD' - 0 - betaPtr "
"g - - 0 true useDeleteList",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_transpose",1086,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__dict_KinematicFitterLN_TMatrixD),-1,0,2,3,4,0,
"u 'TMatrixD' - 11 - alpha g - - 0 true useDeleteList",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_transpose",1086,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__dict_KinematicFitterLN_TMatrixD),-1,0,2,3,4,0,
"U 'TMatrixD' - 0 - alphaPtr g - - 0 true useDeleteList",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_cleanupMatrixPtrs",1893,(G__InterfaceMethod)NULL,121,-1,-1,0,0,3,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("_sq",323,(G__InterfaceMethod)NULL,100,-1,-1,0,1,3,4,0,"d - - 0 - x",(char*)NULL,(void*)NULL,0);
   // automatic copy constructor
   G__memfunc_setup("KinematicFitter",1539,G__dict_KinematicFitter_559_5_6,(int)('i'),G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter),-1,0,1,1,1,0,"u 'KinematicFitter' - 11 - -",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~KinematicFitter",1665,G__dict_KinematicFitter_559_6_6,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   // automatic assignment operator
   G__memfunc_setup("operator=",937,G__dict_KinematicFitter_559_7_6,(int)('u'),G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter),-1,1,1,1,1,0,"u 'KinematicFitter' - 11 - -",(char*)NULL,(void*)NULL,0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncdict_KinematicFitter() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaldict_KinematicFitter() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcdict_KinematicFitter() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__dict_KinematicFitterLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_vectorlEintcOallocatorlEintgRsPgRcLcLiterator = { "vector<int,allocator<int> >::iterator" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<unsigned int,allocator<unsigned int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgR = { "map<int,int,less<int>,allocator<pair<const int,int> > >" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgRcLcLiterator = { "map<int,int,less<int>,allocator<pair<const int,int> > >::iterator" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR = { "set<int,less<int>,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgRcLcLiterator = { "set<int,less<int>,allocator<int> >::iterator" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_TMatrixD = { "TMatrixD" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_TLorentzVector = { "TLorentzVector" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_KinematicFitter = { "KinematicFitter" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_KinematicFittercLcLdA = { "KinematicFitter::$" , 101 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_KinematicFittercLcLInOutType = { "KinematicFitter::InOutType" , 101 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_KinematicFittercLcLConstraintType = { "KinematicFitter::ConstraintType" , 101 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_KinematicFittercLcLCovarianceMode = { "KinematicFitter::CovarianceMode" , 101 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR = { "vector<TLorentzVector,allocator<TLorentzVector> >" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TLorentzVector,allocator<TLorentzVector> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR = { "vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiterator = { "vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >::iterator" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_vectorlETMatrixDcOallocatorlETMatrixDgRsPgR = { "vector<TMatrixD,allocator<TMatrixD> >" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETMatrixDcOallocatorlETMatrixDgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TMatrixD,allocator<TMatrixD> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_vectorlETMatrixDmUcOallocatorlETMatrixDmUgRsPgR = { "vector<TMatrixD*,allocator<TMatrixD*> >" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETMatrixDmUcOallocatorlETMatrixDmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TMatrixD*,allocator<TMatrixD*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_KinematicFittercLcLConstraintStruct = { "KinematicFitter::ConstraintStruct" , 115 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLConstraintStructcOallocatorlEKinematicFittercLcLConstraintStructgRsPgR = { "vector<KinematicFitter::ConstraintStruct,allocator<KinematicFitter::ConstraintStruct> >" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLConstraintStructcOallocatorlEKinematicFittercLcLConstraintStructgRsPgRcLcLiterator = { "vector<KinematicFitter::ConstraintStruct,allocator<KinematicFitter::ConstraintStruct> >::iterator" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEKinematicFittercLcLConstraintStructcOallocatorlEKinematicFittercLcLConstraintStructgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<KinematicFitter::ConstraintStruct,allocator<KinematicFitter::ConstraintStruct> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLVirtualParticlecOallocatorlEKinematicFittercLcLVirtualParticlegRsPgR = { "vector<KinematicFitter::VirtualParticle,allocator<KinematicFitter::VirtualParticle> >" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLVirtualParticlecOallocatorlEKinematicFittercLcLVirtualParticlegRsPgRcLcLiterator = { "vector<KinematicFitter::VirtualParticle,allocator<KinematicFitter::VirtualParticle> >::iterator" , 99 , -1 };
G__linked_taginfo G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEKinematicFittercLcLVirtualParticlecOallocatorlEKinematicFittercLcLVirtualParticlegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<KinematicFitter::VirtualParticle,allocator<KinematicFitter::VirtualParticle> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtabledict_KinematicFitter() {
  G__dict_KinematicFitterLN_string.tagnum = -1 ;
  G__dict_KinematicFitterLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_vectorlEintcOallocatorlEintgRsPgRcLcLiterator.tagnum = -1 ;
  G__dict_KinematicFitterLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgRcLcLiterator.tagnum = -1 ;
  G__dict_KinematicFitterLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgRcLcLiterator.tagnum = -1 ;
  G__dict_KinematicFitterLN_TMatrixD.tagnum = -1 ;
  G__dict_KinematicFitterLN_TLorentzVector.tagnum = -1 ;
  G__dict_KinematicFitterLN_KinematicFitter.tagnum = -1 ;
  G__dict_KinematicFitterLN_KinematicFittercLcLdA.tagnum = -1 ;
  G__dict_KinematicFitterLN_KinematicFittercLcLInOutType.tagnum = -1 ;
  G__dict_KinematicFitterLN_KinematicFittercLcLConstraintType.tagnum = -1 ;
  G__dict_KinematicFitterLN_KinematicFittercLcLCovarianceMode.tagnum = -1 ;
  G__dict_KinematicFitterLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiterator.tagnum = -1 ;
  G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_vectorlETMatrixDcOallocatorlETMatrixDgRsPgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETMatrixDcOallocatorlETMatrixDgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_vectorlETMatrixDmUcOallocatorlETMatrixDmUgRsPgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETMatrixDmUcOallocatorlETMatrixDmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_KinematicFittercLcLConstraintStruct.tagnum = -1 ;
  G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLConstraintStructcOallocatorlEKinematicFittercLcLConstraintStructgRsPgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLConstraintStructcOallocatorlEKinematicFittercLcLConstraintStructgRsPgRcLcLiterator.tagnum = -1 ;
  G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEKinematicFittercLcLConstraintStructcOallocatorlEKinematicFittercLcLConstraintStructgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLVirtualParticlecOallocatorlEKinematicFittercLcLVirtualParticlegRsPgR.tagnum = -1 ;
  G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLVirtualParticlecOallocatorlEKinematicFittercLcLVirtualParticlegRsPgRcLcLiterator.tagnum = -1 ;
  G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEKinematicFittercLcLVirtualParticlecOallocatorlEKinematicFittercLcLVirtualParticlegRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtabledict_KinematicFitter() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_string);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEintcOallocatorlEintgRsPgRcLcLiterator);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgRcLcLiterator);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgRcLcLiterator);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_TMatrixD);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_TLorentzVector);
   G__tagtable_setup(G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFitter),sizeof(KinematicFitter),-1,1280,(char*)NULL,G__setup_memvarKinematicFitter,G__setup_memfuncKinematicFitter);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFittercLcLdA);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFittercLcLInOutType);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFittercLcLConstraintType);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFittercLcLCovarianceMode);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiterator);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETMatrixDcOallocatorlETMatrixDgRsPgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETMatrixDcOallocatorlETMatrixDgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlETMatrixDmUcOallocatorlETMatrixDmUgRsPgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlETMatrixDmUcOallocatorlETMatrixDmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_KinematicFittercLcLConstraintStruct);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLConstraintStructcOallocatorlEKinematicFittercLcLConstraintStructgRsPgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLConstraintStructcOallocatorlEKinematicFittercLcLConstraintStructgRsPgRcLcLiterator);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEKinematicFittercLcLConstraintStructcOallocatorlEKinematicFittercLcLConstraintStructgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLVirtualParticlecOallocatorlEKinematicFittercLcLVirtualParticlegRsPgR);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_vectorlEKinematicFittercLcLVirtualParticlecOallocatorlEKinematicFittercLcLVirtualParticlegRsPgRcLcLiterator);
   G__get_linked_tagnum(&G__dict_KinematicFitterLN_reverse_iteratorlEvectorlEKinematicFittercLcLVirtualParticlecOallocatorlEKinematicFittercLcLVirtualParticlegRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupdict_KinematicFitter(void) {
  G__check_setup_version(30051515,"G__cpp_setupdict_KinematicFitter()");
  G__set_cpp_environmentdict_KinematicFitter();
  G__cpp_setup_tagtabledict_KinematicFitter();

  G__cpp_setup_inheritancedict_KinematicFitter();

  G__cpp_setup_typetabledict_KinematicFitter();

  G__cpp_setup_memvardict_KinematicFitter();

  G__cpp_setup_memfuncdict_KinematicFitter();
  G__cpp_setup_globaldict_KinematicFitter();
  G__cpp_setup_funcdict_KinematicFitter();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncdict_KinematicFitter();
  return;
}
class G__cpp_setup_initdict_KinematicFitter {
  public:
    G__cpp_setup_initdict_KinematicFitter() { G__add_setup_func("dict_KinematicFitter",(G__incsetup)(&G__cpp_setupdict_KinematicFitter)); G__call_setup_funcs(); }
   ~G__cpp_setup_initdict_KinematicFitter() { G__remove_setup_func("dict_KinematicFitter"); }
};
G__cpp_setup_initdict_KinematicFitter G__cpp_setup_initializerdict_KinematicFitter;

