//
// File generated by /cdf/code/cdfsoft/products/root/v5_22_00j-GCC_3_4_6/Linux+2.6/bin/rootcint at Sun Nov  7 18:30:26 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "dict_BinNormClass.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void BinNormClass_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void BinNormClass_Dictionary();
   static void *new_BinNormClass(void *p = 0);
   static void *newArray_BinNormClass(Long_t size, void *p);
   static void delete_BinNormClass(void *p);
   static void deleteArray_BinNormClass(void *p);
   static void destruct_BinNormClass(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::BinNormClass*)
   {
      ::BinNormClass *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::BinNormClass),0);
      static ::ROOT::TGenericClassInfo 
         instance("BinNormClass", "interface/BinNormClass.h", 15,
                  typeid(::BinNormClass), DefineBehavior(ptr, ptr),
                  0, &BinNormClass_Dictionary, isa_proxy, 0,
                  sizeof(::BinNormClass) );
      instance.SetNew(&new_BinNormClass);
      instance.SetNewArray(&newArray_BinNormClass);
      instance.SetDelete(&delete_BinNormClass);
      instance.SetDeleteArray(&deleteArray_BinNormClass);
      instance.SetDestructor(&destruct_BinNormClass);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::BinNormClass*)
   {
      return GenerateInitInstanceLocal((::BinNormClass*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::BinNormClass*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void BinNormClass_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::BinNormClass*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_BinNormClass(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BinNormClass : new ::BinNormClass;
   }
   static void *newArray_BinNormClass(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BinNormClass[nElements] : new ::BinNormClass[nElements];
   }
   // Wrapper around operator delete
   static void delete_BinNormClass(void *p) {
      delete ((::BinNormClass*)p);
   }
   static void deleteArray_BinNormClass(void *p) {
      delete [] ((::BinNormClass*)p);
   }
   static void destruct_BinNormClass(void *p) {
      typedef ::BinNormClass current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::BinNormClass

/********************************************************
* objects/dict_BinNormClass.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && (__GNUC__ > 3) && (__GNUC_MINOR__ > 1)
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtabledict_BinNormClass();

extern "C" void G__set_cpp_environmentdict_BinNormClass() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("BinNormClass.h");
  G__cpp_reset_tagtabledict_BinNormClass();
}
#include <new>
extern "C" int G__cpp_dllrevdict_BinNormClass() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* BinNormClass */
static int G__dict_BinNormClass_502_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BinNormClass* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BinNormClass[n];
     } else {
       p = new((void*) gvp) BinNormClass[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BinNormClass;
     } else {
       p = new((void*) gvp) BinNormClass;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BinNormClass* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new BinNormClass((double) G__double(libp->para[0]));
   } else {
     p = new((void*) gvp) BinNormClass((double) G__double(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BinNormClass* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 4
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new BinNormClass(
(double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3]));
   } else {
     p = new((void*) gvp) BinNormClass(
(double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BinNormClass* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new BinNormClass(
*(BinNormClass::ISet*) libp->para[0].ref, *(BinNormClass::ISet*) libp->para[1].ref
, (double) G__double(libp->para[2]));
   } else {
     p = new((void*) gvp) BinNormClass(
*(BinNormClass::ISet*) libp->para[0].ref, *(BinNormClass::ISet*) libp->para[1].ref
, (double) G__double(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BinNormClass* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 6
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new BinNormClass(
*(BinNormClass::ISet*) libp->para[0].ref, *(BinNormClass::ISet*) libp->para[1].ref
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (double) G__double(libp->para[4]), (double) G__double(libp->para[5]));
   } else {
     p = new((void*) gvp) BinNormClass(
*(BinNormClass::ISet*) libp->para[0].ref, *(BinNormClass::ISet*) libp->para[1].ref
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (double) G__double(libp->para[4]), (double) G__double(libp->para[5]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BinNormClass*) G__getstructoffset())->setBinSet(*(BinNormClass::ISet*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BinNormClass*) G__getstructoffset())->setParamIndex((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BinNormClass*) G__getstructoffset())->setStartingValue((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const BinNormClass*) G__getstructoffset())->setVerbose((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const BinNormClass*) G__getstructoffset())->startingValue());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const BinNormClass*) G__getstructoffset())->paramIndex());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const BinNormClass*) G__getstructoffset())->start());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const BinNormClass*) G__getstructoffset())->stop());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const BinNormClass*) G__getstructoffset())->step());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BinNormClass*) G__getstructoffset())->setStart((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BinNormClass*) G__getstructoffset())->setStop((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BinNormClass*) G__getstructoffset())->setStep((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BinNormClass*) G__getstructoffset())->setStartStopStep((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const StartStopStep& obj = ((const BinNormClass*) G__getstructoffset())->startStopStep();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const BinNormClass*) G__getstructoffset())->functoidPtr());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const BinNormClass*) G__getstructoffset())->index((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const BinNormClass*) G__getstructoffset())->factor((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (double) G__double(libp->para[2]), (const double*) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BinNormClass*) G__getstructoffset())->setTempSet(*(BinNormClass::ISet*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BinNormClass*) G__getstructoffset())->setFunctoid(*(BinNormFunctoid*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BinNormClass*) G__getstructoffset())->setFunctoid((int) G__int(libp->para[0]), *(BinNormFunctoid*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      BinNormClass::insertRangeIntoSet(*(BinNormClass::ISet*) libp->para[0].ref, (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormClass_502_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      BinNormClass::outputISet(*(BinNormClass::ISet*) libp->para[0].ref, *(ostream*) libp->para[1].ref);
      G__setnull(result7);
      break;
   case 1:
      BinNormClass::outputISet(*(BinNormClass::ISet*) libp->para[0].ref);
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__dict_BinNormClass_502_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   BinNormClass* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new BinNormClass(*(BinNormClass*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef BinNormClass G__TBinNormClass;
static int G__dict_BinNormClass_502_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (BinNormClass*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((BinNormClass*) (soff+(sizeof(BinNormClass)*i)))->~G__TBinNormClass();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (BinNormClass*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((BinNormClass*) (soff))->~G__TBinNormClass();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__dict_BinNormClass_502_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BinNormClass* dest = (BinNormClass*) G__getstructoffset();
   *dest = *(BinNormClass*) libp->para[0].ref;
   const BinNormClass& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* BinNormClass */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncdict_BinNormClass {
 public:
  G__Sizep2memfuncdict_BinNormClass(): p(&G__Sizep2memfuncdict_BinNormClass::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncdict_BinNormClass::*p)();
};

size_t G__get_sizep2memfuncdict_BinNormClass()
{
  G__Sizep2memfuncdict_BinNormClass a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancedict_BinNormClass() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetabledict_BinNormClass() {

   /* Setting up typedef entry */
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_BinNormClassLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_BinNormClassLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_BinNormClassLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_BinNormClassLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,BinNormFunctoid*>",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_maplEintcOBinNormFunctoidmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBinNormFunctoidmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,BinNormFunctoid*,less<int> >",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_maplEintcOBinNormFunctoidmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBinNormFunctoidmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<StartStopStep>",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_vectorlEStartStopStepcOallocatorlEStartStopStepgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_reverse_iteratorlEvectorlEStartStopStepcOallocatorlEStartStopStepgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_BinNormClassLN_vectorlEStartStopStepcOallocatorlEStartStopStepgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_reverse_iteratorlEvectorlEStartStopStepcOallocatorlEStartStopStepgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_BinNormClassLN_vectorlEStartStopStepcOallocatorlEStartStopStepgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ISet",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR),0,G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BinNormClass>",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_vectorlEBinNormClasscOallocatorlEBinNormClassgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_reverse_iteratorlEvectorlEBinNormClasscOallocatorlEBinNormClassgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_BinNormClassLN_vectorlEBinNormClasscOallocatorlEBinNormClassgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_reverse_iteratorlEvectorlEBinNormClasscOallocatorlEBinNormClassgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_BinNormClassLN_vectorlEBinNormClasscOallocatorlEBinNormClassgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("Vec",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_vectorlEBinNormClasscOallocatorlEBinNormClassgRsPgR),0,G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ISetIter",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ISetConstIter",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("VecConstIter",117,G__get_linked_tagnum(&G__dict_BinNormClassLN_vectorlEBinNormClasscOallocatorlEBinNormClassgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* BinNormClass */
static void G__setup_memvarBinNormClass(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass));
   { BinNormClass *p; p=(BinNormClass*)0x1000; if (p) { }
   G__memvar_setup((void*)(&BinNormClass::kMinValue),100,0,1,-1,-1,-2,1,"kMinValue=",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClasscLcLdA),-1,-2,1,"kNegativeNumber=-1",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClasscLcLdA),-1,-2,1,"kNumParams=5",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__dict_BinNormClassLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR),G__defined_typename("ISet"),-1,4,"m_templateSet=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__dict_BinNormClassLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR),G__defined_typename("ISet"),-1,4,"m_binSet=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"m_value=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"m_paramIndex=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__dict_BinNormClassLN_StartStopStep),-1,-1,4,"m_startStopStep=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_verbose=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormFunctoid),-1,-1,4,"m_functoidPtr=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__dict_BinNormClassLN_maplEintcOBinNormFunctoidmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBinNormFunctoidmUgRsPgRsPgR),G__defined_typename("IFMap"),-1,4,"m_functoidMap=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvardict_BinNormClass() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncBinNormClass(void) {
   /* BinNormClass */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass));
   G__memfunc_setup("BinNormClass",1195,G__dict_BinNormClass_502_0_1, 105, G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BinNormClass",1195,G__dict_BinNormClass_502_0_2, 105, G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass), -1, 0, 1, 1, 1, 0, "d - - 0 - startingValue", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BinNormClass",1195,G__dict_BinNormClass_502_0_3, 105, G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass), -1, 0, 4, 1, 1, 0, 
"d - - 0 - startingValue d - - 0 - start "
"d - - 0 - stop d - - 0 - step", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BinNormClass",1195,G__dict_BinNormClass_502_0_4, 105, G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass), -1, 0, 3, 1, 1, 0, 
"u 'set<int,less<int>,allocator<int> >' 'BinNormClass::ISet' 11 - tempSet u 'set<int,less<int>,allocator<int> >' 'BinNormClass::ISet' 11 - binSet "
"d - - 0 - startingValue", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BinNormClass",1195,G__dict_BinNormClass_502_0_5, 105, G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass), -1, 0, 6, 1, 1, 0, 
"u 'set<int,less<int>,allocator<int> >' 'BinNormClass::ISet' 11 - tempSet u 'set<int,less<int>,allocator<int> >' 'BinNormClass::ISet' 11 - binSet "
"d - - 0 - startingValue d - - 0 - start "
"d - - 0 - stop d - - 0 - step", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setBinSet",913,G__dict_BinNormClass_502_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "u 'set<int,less<int>,allocator<int> >' 'BinNormClass::ISet' 11 - binSet", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setParamIndex",1333,G__dict_BinNormClass_502_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setStartingValue",1685,G__dict_BinNormClass_502_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setVerbose",1058,G__dict_BinNormClass_502_0_9, 121, -1, -1, 0, 1, 1, 1, 8, "g - - 0 - verbose", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("startingValue",1385,G__dict_BinNormClass_502_0_10, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("paramIndex",1033,G__dict_BinNormClass_502_0_11, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("start",558,G__dict_BinNormClass_502_0_12, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("stop",454,G__dict_BinNormClass_502_0_13, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("step",444,G__dict_BinNormClass_502_0_14, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setStart",858,G__dict_BinNormClass_502_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - start", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setStop",754,G__dict_BinNormClass_502_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - stop", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setStep",744,G__dict_BinNormClass_502_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - step", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setStartStopStep",1692,G__dict_BinNormClass_502_0_18, 121, -1, -1, 0, 3, 1, 1, 0, 
"d - - 0 - start d - - 0 - stop "
"d - - 0 - step", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("startStopStep",1392,G__dict_BinNormClass_502_0_19, 117, G__get_linked_tagnum(&G__dict_BinNormClassLN_StartStopStep), -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("functoidPtr",1170,G__dict_BinNormClass_502_0_20, 85, G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormFunctoid), -1, 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("index",536,G__dict_BinNormClass_502_0_21, 105, -1, -1, 0, 2, 1, 1, 8, 
"i - - 0 - tempIndex i - - 0 - binIndex", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("factor",639,G__dict_BinNormClass_502_0_22, 100, -1, -1, 0, 4, 1, 1, 8, 
"i - - 0 - tempIndex i - - 0 - binIndex "
"d - - 0 - value D - - 10 - paramArray", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setTempSet",1038,G__dict_BinNormClass_502_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "u 'set<int,less<int>,allocator<int> >' 'BinNormClass::ISet' 11 - tempSet", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setFunctoid",1160,G__dict_BinNormClass_502_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "u 'BinNormFunctoid' - 1 - functoid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setFunctoid",1160,G__dict_BinNormClass_502_0_25, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - tempIndex u 'BinNormFunctoid' - 1 - functoid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("insertRangeIntoSet",1864,G__dict_BinNormClass_502_0_26, 121, -1, -1, 0, 3, 3, 1, 0, 
"u 'set<int,less<int>,allocator<int> >' 'BinNormClass::ISet' 1 - theset i - - 0 - lower "
"i - - 0 - upper", (char*)NULL, (void*) (void (*)(BinNormClass::ISet&, int, int))(&BinNormClass::insertRangeIntoSet), 0);
   G__memfunc_setup("outputISet",1062,G__dict_BinNormClass_502_0_27, 121, -1, -1, 0, 2, 3, 1, 0, 
"u 'set<int,less<int>,allocator<int> >' 'BinNormClass::ISet' 11 - theset u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 'std::cout' o_stream", (char*)NULL, (void*) (void (*)(const BinNormClass::ISet&, ostream&))(&BinNormClass::outputISet), 0);
   // automatic copy constructor
   G__memfunc_setup("BinNormClass", 1195, G__dict_BinNormClass_502_0_28, (int) ('i'), G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass), -1, 0, 1, 1, 1, 0, "u 'BinNormClass' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BinNormClass", 1321, G__dict_BinNormClass_502_0_29, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__dict_BinNormClass_502_0_30, (int) ('u'), G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass), -1, 1, 1, 1, 1, 0, "u 'BinNormClass' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncdict_BinNormClass() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaldict_BinNormClass() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcdict_BinNormClass() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__dict_BinNormClassLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__dict_BinNormClassLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR = { "basic_ostream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G__dict_BinNormClassLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__dict_BinNormClassLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_BinNormClassLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR = { "set<int,less<int>,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__dict_BinNormClassLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgRcLcLiterator = { "set<int,less<int>,allocator<int> >::iterator" , 99 , -1 };
G__linked_taginfo G__dict_BinNormClassLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__dict_BinNormClassLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_BinNormClassLN_BinNormFunctoid = { "BinNormFunctoid" , 99 , -1 };
G__linked_taginfo G__dict_BinNormClassLN_maplEintcOBinNormFunctoidmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBinNormFunctoidmUgRsPgRsPgR = { "map<int,BinNormFunctoid*,less<int>,allocator<pair<const int,BinNormFunctoid*> > >" , 99 , -1 };
G__linked_taginfo G__dict_BinNormClassLN_StartStopStep = { "StartStopStep" , 99 , -1 };
G__linked_taginfo G__dict_BinNormClassLN_vectorlEStartStopStepcOallocatorlEStartStopStepgRsPgR = { "vector<StartStopStep,allocator<StartStopStep> >" , 99 , -1 };
G__linked_taginfo G__dict_BinNormClassLN_reverse_iteratorlEvectorlEStartStopStepcOallocatorlEStartStopStepgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<StartStopStep,allocator<StartStopStep> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_BinNormClassLN_BinNormClass = { "BinNormClass" , 99 , -1 };
G__linked_taginfo G__dict_BinNormClassLN_vectorlEBinNormClasscOallocatorlEBinNormClassgRsPgR = { "vector<BinNormClass,allocator<BinNormClass> >" , 99 , -1 };
G__linked_taginfo G__dict_BinNormClassLN_vectorlEBinNormClasscOallocatorlEBinNormClassgRsPgRcLcLiterator = { "vector<BinNormClass,allocator<BinNormClass> >::iterator" , 99 , -1 };
G__linked_taginfo G__dict_BinNormClassLN_reverse_iteratorlEvectorlEBinNormClasscOallocatorlEBinNormClassgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BinNormClass,allocator<BinNormClass> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_BinNormClassLN_BinNormClasscLcLdA = { "BinNormClass::$" , 101 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtabledict_BinNormClass() {
  G__dict_BinNormClassLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__dict_BinNormClassLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G__dict_BinNormClassLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__dict_BinNormClassLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_BinNormClassLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__dict_BinNormClassLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgRcLcLiterator.tagnum = -1 ;
  G__dict_BinNormClassLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__dict_BinNormClassLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_BinNormClassLN_BinNormFunctoid.tagnum = -1 ;
  G__dict_BinNormClassLN_maplEintcOBinNormFunctoidmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBinNormFunctoidmUgRsPgRsPgR.tagnum = -1 ;
  G__dict_BinNormClassLN_StartStopStep.tagnum = -1 ;
  G__dict_BinNormClassLN_vectorlEStartStopStepcOallocatorlEStartStopStepgRsPgR.tagnum = -1 ;
  G__dict_BinNormClassLN_reverse_iteratorlEvectorlEStartStopStepcOallocatorlEStartStopStepgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_BinNormClassLN_BinNormClass.tagnum = -1 ;
  G__dict_BinNormClassLN_vectorlEBinNormClasscOallocatorlEBinNormClassgRsPgR.tagnum = -1 ;
  G__dict_BinNormClassLN_vectorlEBinNormClasscOallocatorlEBinNormClassgRsPgRcLcLiterator.tagnum = -1 ;
  G__dict_BinNormClassLN_reverse_iteratorlEvectorlEBinNormClasscOallocatorlEBinNormClassgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_BinNormClassLN_BinNormClasscLcLdA.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtabledict_BinNormClass() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__dict_BinNormClassLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_BinNormClassLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_BinNormClassLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_BinNormClassLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dict_BinNormClassLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_BinNormClassLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G__dict_BinNormClassLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_BinNormClassLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dict_BinNormClassLN_BinNormFunctoid);
   G__get_linked_tagnum_fwd(&G__dict_BinNormClassLN_maplEintcOBinNormFunctoidmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBinNormFunctoidmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_BinNormClassLN_StartStopStep);
   G__get_linked_tagnum_fwd(&G__dict_BinNormClassLN_vectorlEStartStopStepcOallocatorlEStartStopStepgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_BinNormClassLN_reverse_iteratorlEvectorlEStartStopStepcOallocatorlEStartStopStepgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__dict_BinNormClassLN_BinNormClass),sizeof(BinNormClass),-1,33024,(char*)NULL,G__setup_memvarBinNormClass,G__setup_memfuncBinNormClass);
   G__get_linked_tagnum_fwd(&G__dict_BinNormClassLN_vectorlEBinNormClasscOallocatorlEBinNormClassgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_BinNormClassLN_vectorlEBinNormClasscOallocatorlEBinNormClassgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G__dict_BinNormClassLN_reverse_iteratorlEvectorlEBinNormClasscOallocatorlEBinNormClassgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dict_BinNormClassLN_BinNormClasscLcLdA);
}
extern "C" void G__cpp_setupdict_BinNormClass(void) {
  G__check_setup_version(30051515,"G__cpp_setupdict_BinNormClass()");
  G__set_cpp_environmentdict_BinNormClass();
  G__cpp_setup_tagtabledict_BinNormClass();

  G__cpp_setup_inheritancedict_BinNormClass();

  G__cpp_setup_typetabledict_BinNormClass();

  G__cpp_setup_memvardict_BinNormClass();

  G__cpp_setup_memfuncdict_BinNormClass();
  G__cpp_setup_globaldict_BinNormClass();
  G__cpp_setup_funcdict_BinNormClass();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncdict_BinNormClass();
  return;
}
class G__cpp_setup_initdict_BinNormClass {
  public:
    G__cpp_setup_initdict_BinNormClass() { G__add_setup_func("dict_BinNormClass",(G__incsetup)(&G__cpp_setupdict_BinNormClass)); G__call_setup_funcs(); }
   ~G__cpp_setup_initdict_BinNormClass() { G__remove_setup_func("dict_BinNormClass"); }
};
G__cpp_setup_initdict_BinNormClass G__cpp_setup_initializerdict_BinNormClass;

