//
// File generated by /cdf/code/cdfsoft/products/root/v5_22_00j-GCC_3_4_6/Linux+2.6/bin/rootcint at Sun Nov  7 18:30:26 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "dict_CLPTrapezoid.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void CLPTrapezoid_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void delete_CLPTrapezoid(void *p);
   static void deleteArray_CLPTrapezoid(void *p);
   static void destruct_CLPTrapezoid(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::CLPTrapezoid*)
   {
      ::CLPTrapezoid *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::CLPTrapezoid >(0);
      static ::ROOT::TGenericClassInfo 
         instance("CLPTrapezoid", ::CLPTrapezoid::Class_Version(), "interface/CLPTrapezoid.h", 12,
                  typeid(::CLPTrapezoid), DefineBehavior(ptr, ptr),
                  &::CLPTrapezoid::Dictionary, isa_proxy, 0,
                  sizeof(::CLPTrapezoid) );
      instance.SetDelete(&delete_CLPTrapezoid);
      instance.SetDeleteArray(&deleteArray_CLPTrapezoid);
      instance.SetDestructor(&destruct_CLPTrapezoid);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::CLPTrapezoid*)
   {
      return GenerateInitInstanceLocal((::CLPTrapezoid*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::CLPTrapezoid*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *CLPTrapezoid::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *CLPTrapezoid::Class_Name()
{
   return "CLPTrapezoid";
}

//______________________________________________________________________________
const char *CLPTrapezoid::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CLPTrapezoid*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int CLPTrapezoid::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CLPTrapezoid*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void CLPTrapezoid::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CLPTrapezoid*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *CLPTrapezoid::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CLPTrapezoid*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void CLPTrapezoid::Streamer(TBuffer &R__b)
{
   // Stream an object of class CLPTrapezoid.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> m_lowerX;
      R__b >> m_upperX;
      R__b >> m_lowerY;
      R__b >> m_upperY;
      R__b >> m_integral;
      R__b >> m_totalIntegral;
      R__b >> m_position;
      R__b.CheckByteCount(R__s, R__c, CLPTrapezoid::IsA());
   } else {
      R__c = R__b.WriteVersion(CLPTrapezoid::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << m_lowerX;
      R__b << m_upperX;
      R__b << m_lowerY;
      R__b << m_upperY;
      R__b << m_integral;
      R__b << m_totalIntegral;
      R__b << m_position;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void CLPTrapezoid::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class CLPTrapezoid.
      TClass *R__cl = ::CLPTrapezoid::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "m_lowerX", &m_lowerX);
      R__insp.Inspect(R__cl, R__parent, "m_upperX", &m_upperX);
      R__insp.Inspect(R__cl, R__parent, "m_lowerY", &m_lowerY);
      R__insp.Inspect(R__cl, R__parent, "m_upperY", &m_upperY);
      R__insp.Inspect(R__cl, R__parent, "m_integral", &m_integral);
      R__insp.Inspect(R__cl, R__parent, "m_totalIntegral", &m_totalIntegral);
      R__insp.Inspect(R__cl, R__parent, "m_position", &m_position);
      TObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_CLPTrapezoid(void *p) {
      delete ((::CLPTrapezoid*)p);
   }
   static void deleteArray_CLPTrapezoid(void *p) {
      delete [] ((::CLPTrapezoid*)p);
   }
   static void destruct_CLPTrapezoid(void *p) {
      typedef ::CLPTrapezoid current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::CLPTrapezoid

/********************************************************
* objects/dict_CLPTrapezoid.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && (__GNUC__ > 3) && (__GNUC_MINOR__ > 1)
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtabledict_CLPTrapezoid();

extern "C" void G__set_cpp_environmentdict_CLPTrapezoid() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("CLPTrapezoid.h");
  G__cpp_reset_tagtabledict_CLPTrapezoid();
}
#include <new>
extern "C" int G__cpp_dllrevdict_CLPTrapezoid() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* CLPTrapezoid */
static int G__dict_CLPTrapezoid_199_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CLPTrapezoid* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new CLPTrapezoid((double) G__double(libp->para[0]), (double) G__double(libp->para[1]));
   } else {
     p = new((void*) gvp) CLPTrapezoid((double) G__double(libp->para[0]), (double) G__double(libp->para[1]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_CLPTrapezoid));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const CLPTrapezoid*) G__getstructoffset())->operator>(*(CLPTrapezoid*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const CLPTrapezoid*) G__getstructoffset())->operator<(*(CLPTrapezoid*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const CLPTrapezoid*) G__getstructoffset())->lowerX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const CLPTrapezoid*) G__getstructoffset())->upperX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const CLPTrapezoid*) G__getstructoffset())->lowerY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const CLPTrapezoid*) G__getstructoffset())->upperY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const CLPTrapezoid*) G__getstructoffset())->totalIntegral());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const CLPTrapezoid*) G__getstructoffset())->minY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const CLPTrapezoid*) G__getstructoffset())->maxY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const CLPTrapezoid*) G__getstructoffset())->position());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTrapezoid*) G__getstructoffset())->setLowerX((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTrapezoid*) G__getstructoffset())->setUpperX((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTrapezoid*) G__getstructoffset())->setLowerY((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTrapezoid*) G__getstructoffset())->setUpperY((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTrapezoid*) G__getstructoffset())->setTotalIntegral((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTrapezoid*) G__getstructoffset())->setPosition((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const CLPTrapezoid*) G__getstructoffset())->integral());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTrapezoid*) G__getstructoffset())->scale((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const CLPTrapezoid*) G__getstructoffset())->positionWRT((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const CLPTrapezoid*) G__getstructoffset())->hasVerticalOverlapWith(*(CLPTrapezoid*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const CLPTrapezoid*) G__getstructoffset())->absSlope());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      CLPTrapezoid::limits(*(CLPTrapezoid::Vec*) libp->para[0].ref, *(double*) G__Doubleref(&libp->para[1])
, *(double*) G__Doubleref(&libp->para[2]), (double) G__double(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      CLPTrapezoid::limits(*(CLPTrapezoid::Vec*) libp->para[0].ref, *(double*) G__Doubleref(&libp->para[1])
, *(double*) G__Doubleref(&libp->para[2]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) CLPTrapezoid::minMaxArea(*(double*) G__Doubleref(&libp->para[0]), *(double*) G__Doubleref(&libp->para[1])
, *(CLPTrapezoid::VecConstIter*) libp->para[2].ref, *(CLPTrapezoid::VecConstIter*) libp->para[3].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      G__letdouble(result7, 100, (double) CLPTrapezoid::findYintersect(*(CLPTrapezoid::Vec*) libp->para[0].ref, (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])));
      break;
   case 3:
      G__letdouble(result7, 100, (double) CLPTrapezoid::findYintersect(*(CLPTrapezoid::Vec*) libp->para[0].ref, (double) G__double(libp->para[1])
, (double) G__double(libp->para[2])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) CLPTrapezoid::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CLPTrapezoid::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) CLPTrapezoid::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      CLPTrapezoid::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTrapezoid*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CLPTrapezoid::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CLPTrapezoid::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CLPTrapezoid::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTrapezoid_199_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CLPTrapezoid::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__dict_CLPTrapezoid_199_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   CLPTrapezoid* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new CLPTrapezoid(*(CLPTrapezoid*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_CLPTrapezoid));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef CLPTrapezoid G__TCLPTrapezoid;
static int G__dict_CLPTrapezoid_199_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (CLPTrapezoid*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((CLPTrapezoid*) (soff+(sizeof(CLPTrapezoid)*i)))->~G__TCLPTrapezoid();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (CLPTrapezoid*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((CLPTrapezoid*) (soff))->~G__TCLPTrapezoid();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__dict_CLPTrapezoid_199_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CLPTrapezoid* dest = (CLPTrapezoid*) G__getstructoffset();
   *dest = *(CLPTrapezoid*) libp->para[0].ref;
   const CLPTrapezoid& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* CLPTrapezoid */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncdict_CLPTrapezoid {
 public:
  G__Sizep2memfuncdict_CLPTrapezoid(): p(&G__Sizep2memfuncdict_CLPTrapezoid::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncdict_CLPTrapezoid::*p)();
};

size_t G__get_sizep2memfuncdict_CLPTrapezoid()
{
  G__Sizep2memfuncdict_CLPTrapezoid a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancedict_CLPTrapezoid() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_CLPTrapezoid))) {
     CLPTrapezoid *G__Lderived;
     G__Lderived=(CLPTrapezoid*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_CLPTrapezoid),G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetabledict_CLPTrapezoid() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<CLPTrapezoid>",117,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_vectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_reverse_iteratorlEvectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_vectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_reverse_iteratorlEvectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_vectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("Vec",117,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_vectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgR),0,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_CLPTrapezoid));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("VecIter",117,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_vectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_CLPTrapezoid));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("VecConstIter",117,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_vectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_CLPTrapezoid));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("VecConstRevIter",117,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_reverse_iteratorlEvectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_CLPTrapezoid));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("DVec",117,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_CLPTrapezoid));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* CLPTrapezoid */
static void G__setup_memvarCLPTrapezoid(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_CLPTrapezoid));
   { CLPTrapezoid *p; p=(CLPTrapezoid*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_CLPTrapezoidcLcLdA),-1,-2,1,"kToTheRight=1",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_CLPTrapezoidcLcLdA),-1,-2,1,"kToTheLeft=-1",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_CLPTrapezoidcLcLdA),-1,-2,1,"kInside=0",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"m_lowerX=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"m_upperX=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"m_lowerY=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"m_upperY=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"m_integral=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"m_totalIntegral=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"m_position=",0,"for debugging purposes");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvardict_CLPTrapezoid() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncCLPTrapezoid(void) {
   /* CLPTrapezoid */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_CLPTrapezoid));
   G__memfunc_setup("CLPTrapezoid",1169,G__dict_CLPTrapezoid_199_0_1, 105, G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_CLPTrapezoid), -1, 0, 2, 1, 1, 0, 
"d - - 0 - x d - - 0 - y", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator>",938,G__dict_CLPTrapezoid_199_0_2, 103, -1, -1, 0, 1, 1, 1, 8, "u 'CLPTrapezoid' - 11 - rhs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator<",936,G__dict_CLPTrapezoid_199_0_3, 103, -1, -1, 0, 1, 1, 1, 8, "u 'CLPTrapezoid' - 11 - rhs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("lowerX",641,G__dict_CLPTrapezoid_199_0_4, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("upperX",644,G__dict_CLPTrapezoid_199_0_5, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("lowerY",642,G__dict_CLPTrapezoid_199_0_6, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("upperY",645,G__dict_CLPTrapezoid_199_0_7, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("totalIntegral",1370,G__dict_CLPTrapezoid_199_0_8, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("minY",413,G__dict_CLPTrapezoid_199_0_9, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("maxY",415,G__dict_CLPTrapezoid_199_0_10, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("position",885,G__dict_CLPTrapezoid_199_0_11, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setLowerX",941,G__dict_CLPTrapezoid_199_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - lowerX", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setUpperX",944,G__dict_CLPTrapezoid_199_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - upperX", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setLowerY",942,G__dict_CLPTrapezoid_199_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - lowerY", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setUpperY",945,G__dict_CLPTrapezoid_199_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - upperY", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setTotalIntegral",1670,G__dict_CLPTrapezoid_199_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - totalIntegral", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setPosition",1185,G__dict_CLPTrapezoid_199_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - position", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("integral",854,G__dict_CLPTrapezoid_199_0_18, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("scale",520,G__dict_CLPTrapezoid_199_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - factor", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("positionWRT",1138,G__dict_CLPTrapezoid_199_0_20, 105, -1, -1, 0, 1, 1, 1, 8, "d - - 0 - xVal", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("hasVerticalOverlapWith",2283,G__dict_CLPTrapezoid_199_0_21, 103, -1, -1, 0, 1, 1, 1, 8, "u 'CLPTrapezoid' - 11 - rhs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("absSlope",825,G__dict_CLPTrapezoid_199_0_22, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("limits",658,G__dict_CLPTrapezoid_199_0_23, 121, -1, -1, 0, 4, 3, 1, 0, 
"u 'vector<CLPTrapezoid,allocator<CLPTrapezoid> >' 'CLPTrapezoid::Vec' 1 - curve d - - 1 - upperLimit "
"d - - 1 - lowerLimit d - - 0 '0.95' percent", (char*)NULL, (void*) (void (*)(CLPTrapezoid::Vec&, double&, double&, double))(&CLPTrapezoid::limits), 0);
   G__memfunc_setup("minMaxArea",995,G__dict_CLPTrapezoid_199_0_24, 103, -1, -1, 0, 4, 3, 1, 0, 
"d - - 1 - minArea d - - 1 - maxArea "
"u 'vector<CLPTrapezoid,allocator<CLPTrapezoid> >::iterator' 'CLPTrapezoid::VecConstIter' 11 - alpha u 'vector<CLPTrapezoid,allocator<CLPTrapezoid> >::iterator' 'CLPTrapezoid::VecConstIter' 11 - beta", (char*)NULL, (void*) (bool (*)(double&, double&, const CLPTrapezoid::VecConstIter&, const CLPTrapezoid::VecConstIter&))(&CLPTrapezoid::minMaxArea), 0);
   G__memfunc_setup("findYintersect",1483,G__dict_CLPTrapezoid_199_0_25, 100, -1, -1, 0, 4, 3, 1, 0, 
"u 'vector<CLPTrapezoid,allocator<CLPTrapezoid> >' 'CLPTrapezoid::Vec' 11 - curve d - - 0 - signedStep "
"d - - 0 - yDelta d - - 0 '0.00001' epsilon", (char*)NULL, (void*) (double (*)(const CLPTrapezoid::Vec&, double, double, double))(&CLPTrapezoid::findYintersect), 0);
   G__memfunc_setup("Class",502,G__dict_CLPTrapezoid_199_0_26, 85, G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (TClass* (*)())(&CLPTrapezoid::Class), 0);
   G__memfunc_setup("Class_Name",982,G__dict_CLPTrapezoid_199_0_27, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&CLPTrapezoid::Class_Name), 0);
   G__memfunc_setup("Class_Version",1339,G__dict_CLPTrapezoid_199_0_28, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (Version_t (*)())(&CLPTrapezoid::Class_Version), 0);
   G__memfunc_setup("Dictionary",1046,G__dict_CLPTrapezoid_199_0_29, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (void (*)())(&CLPTrapezoid::Dictionary), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__dict_CLPTrapezoid_199_0_33, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__dict_CLPTrapezoid_199_0_34, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&CLPTrapezoid::DeclFileName), 0);
   G__memfunc_setup("ImplFileLine",1178,G__dict_CLPTrapezoid_199_0_35, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&CLPTrapezoid::ImplFileLine), 0);
   G__memfunc_setup("ImplFileName",1171,G__dict_CLPTrapezoid_199_0_36, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&CLPTrapezoid::ImplFileName), 0);
   G__memfunc_setup("DeclFileLine",1152,G__dict_CLPTrapezoid_199_0_37, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&CLPTrapezoid::DeclFileLine), 0);
   // automatic copy constructor
   G__memfunc_setup("CLPTrapezoid", 1169, G__dict_CLPTrapezoid_199_0_38, (int) ('i'), G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_CLPTrapezoid), -1, 0, 1, 1, 1, 0, "u 'CLPTrapezoid' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~CLPTrapezoid", 1295, G__dict_CLPTrapezoid_199_0_39, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__dict_CLPTrapezoid_199_0_40, (int) ('u'), G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_CLPTrapezoid), -1, 1, 1, 1, 1, 0, "u 'CLPTrapezoid' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncdict_CLPTrapezoid() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaldict_CLPTrapezoid() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcdict_CLPTrapezoid() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__dict_CLPTrapezoidLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__dict_CLPTrapezoidLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__dict_CLPTrapezoidLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__dict_CLPTrapezoidLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__dict_CLPTrapezoidLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPTrapezoidLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPTrapezoidLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPTrapezoidLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_CLPTrapezoidLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPTrapezoidLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_CLPTrapezoidLN_CLPTrapezoid = { "CLPTrapezoid" , 99 , -1 };
G__linked_taginfo G__dict_CLPTrapezoidLN_vectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgR = { "vector<CLPTrapezoid,allocator<CLPTrapezoid> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPTrapezoidLN_vectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgRcLcLiterator = { "vector<CLPTrapezoid,allocator<CLPTrapezoid> >::iterator" , 99 , -1 };
G__linked_taginfo G__dict_CLPTrapezoidLN_reverse_iteratorlEvectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<CLPTrapezoid,allocator<CLPTrapezoid> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_CLPTrapezoidLN_CLPTrapezoidcLcLdA = { "CLPTrapezoid::$" , 101 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtabledict_CLPTrapezoid() {
  G__dict_CLPTrapezoidLN_TClass.tagnum = -1 ;
  G__dict_CLPTrapezoidLN_TBuffer.tagnum = -1 ;
  G__dict_CLPTrapezoidLN_TMemberInspector.tagnum = -1 ;
  G__dict_CLPTrapezoidLN_TObject.tagnum = -1 ;
  G__dict_CLPTrapezoidLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__dict_CLPTrapezoidLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__dict_CLPTrapezoidLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__dict_CLPTrapezoidLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_CLPTrapezoidLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__dict_CLPTrapezoidLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_CLPTrapezoidLN_CLPTrapezoid.tagnum = -1 ;
  G__dict_CLPTrapezoidLN_vectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgR.tagnum = -1 ;
  G__dict_CLPTrapezoidLN_vectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgRcLcLiterator.tagnum = -1 ;
  G__dict_CLPTrapezoidLN_reverse_iteratorlEvectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_CLPTrapezoidLN_CLPTrapezoidcLcLdA.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtabledict_CLPTrapezoid() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__dict_CLPTrapezoidLN_TClass);
   G__get_linked_tagnum_fwd(&G__dict_CLPTrapezoidLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__dict_CLPTrapezoidLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__dict_CLPTrapezoidLN_TObject);
   G__get_linked_tagnum_fwd(&G__dict_CLPTrapezoidLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTrapezoidLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTrapezoidLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTrapezoidLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTrapezoidLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTrapezoidLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__dict_CLPTrapezoidLN_CLPTrapezoid),sizeof(CLPTrapezoid),-1,61440,"CLPTrapezoid Class",G__setup_memvarCLPTrapezoid,G__setup_memfuncCLPTrapezoid);
   G__get_linked_tagnum_fwd(&G__dict_CLPTrapezoidLN_vectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTrapezoidLN_vectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G__dict_CLPTrapezoidLN_reverse_iteratorlEvectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTrapezoidLN_CLPTrapezoidcLcLdA);
}
extern "C" void G__cpp_setupdict_CLPTrapezoid(void) {
  G__check_setup_version(30051515,"G__cpp_setupdict_CLPTrapezoid()");
  G__set_cpp_environmentdict_CLPTrapezoid();
  G__cpp_setup_tagtabledict_CLPTrapezoid();

  G__cpp_setup_inheritancedict_CLPTrapezoid();

  G__cpp_setup_typetabledict_CLPTrapezoid();

  G__cpp_setup_memvardict_CLPTrapezoid();

  G__cpp_setup_memfuncdict_CLPTrapezoid();
  G__cpp_setup_globaldict_CLPTrapezoid();
  G__cpp_setup_funcdict_CLPTrapezoid();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncdict_CLPTrapezoid();
  return;
}
class G__cpp_setup_initdict_CLPTrapezoid {
  public:
    G__cpp_setup_initdict_CLPTrapezoid() { G__add_setup_func("dict_CLPTrapezoid",(G__incsetup)(&G__cpp_setupdict_CLPTrapezoid)); G__call_setup_funcs(); }
   ~G__cpp_setup_initdict_CLPTrapezoid() { G__remove_setup_func("dict_CLPTrapezoid"); }
};
G__cpp_setup_initdict_CLPTrapezoid G__cpp_setup_initializerdict_CLPTrapezoid;

