/********************************************************************
* objects/dict_BinNormFunctoid.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error objects/dict_BinNormFunctoid.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtabledict_BinNormFunctoid();
extern void G__cpp_setup_inheritancedict_BinNormFunctoid();
extern void G__cpp_setup_typetabledict_BinNormFunctoid();
extern void G__cpp_setup_memvardict_BinNormFunctoid();
extern void G__cpp_setup_globaldict_BinNormFunctoid();
extern void G__cpp_setup_memfuncdict_BinNormFunctoid();
extern void G__cpp_setup_funcdict_BinNormFunctoid();
extern void G__set_cpp_environmentdict_BinNormFunctoid();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BinNormFunctoid.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dict_BinNormFunctoidLN_TClass;
extern G__linked_taginfo G__dict_BinNormFunctoidLN_TBuffer;
extern G__linked_taginfo G__dict_BinNormFunctoidLN_TMemberInspector;
extern G__linked_taginfo G__dict_BinNormFunctoidLN_TObject;
extern G__linked_taginfo G__dict_BinNormFunctoidLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__dict_BinNormFunctoidLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__dict_BinNormFunctoidLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dict_BinNormFunctoidLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_BinNormFunctoidLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__dict_BinNormFunctoidLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_BinNormFunctoidLN_BinNormFunctoid;
extern G__linked_taginfo G__dict_BinNormFunctoidLN_maplEintcOBinNormFunctoidmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBinNormFunctoidmUgRsPgRsPgR;
extern G__linked_taginfo G__dict_BinNormFunctoidLN_maplEintcOBinNormFunctoidmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBinNormFunctoidmUgRsPgRsPgRcLcLiterator;

/* STUB derived class for protected member access */
