/********************************************************************
* objects/dict_CLPTrapezoid.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error objects/dict_CLPTrapezoid.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtabledict_CLPTrapezoid();
extern void G__cpp_setup_inheritancedict_CLPTrapezoid();
extern void G__cpp_setup_typetabledict_CLPTrapezoid();
extern void G__cpp_setup_memvardict_CLPTrapezoid();
extern void G__cpp_setup_globaldict_CLPTrapezoid();
extern void G__cpp_setup_memfuncdict_CLPTrapezoid();
extern void G__cpp_setup_funcdict_CLPTrapezoid();
extern void G__set_cpp_environmentdict_CLPTrapezoid();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "CLPTrapezoid.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dict_CLPTrapezoidLN_TClass;
extern G__linked_taginfo G__dict_CLPTrapezoidLN_TBuffer;
extern G__linked_taginfo G__dict_CLPTrapezoidLN_TMemberInspector;
extern G__linked_taginfo G__dict_CLPTrapezoidLN_TObject;
extern G__linked_taginfo G__dict_CLPTrapezoidLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__dict_CLPTrapezoidLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__dict_CLPTrapezoidLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dict_CLPTrapezoidLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_CLPTrapezoidLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__dict_CLPTrapezoidLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_CLPTrapezoidLN_CLPTrapezoid;
extern G__linked_taginfo G__dict_CLPTrapezoidLN_vectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgR;
extern G__linked_taginfo G__dict_CLPTrapezoidLN_vectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgRcLcLiterator;
extern G__linked_taginfo G__dict_CLPTrapezoidLN_reverse_iteratorlEvectorlECLPTrapezoidcOallocatorlECLPTrapezoidgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_CLPTrapezoidLN_CLPTrapezoidcLcLdA;

/* STUB derived class for protected member access */
