/********************************************************************
* objects/dict_BinNormClass.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error objects/dict_BinNormClass.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtabledict_BinNormClass();
extern void G__cpp_setup_inheritancedict_BinNormClass();
extern void G__cpp_setup_typetabledict_BinNormClass();
extern void G__cpp_setup_memvardict_BinNormClass();
extern void G__cpp_setup_globaldict_BinNormClass();
extern void G__cpp_setup_memfuncdict_BinNormClass();
extern void G__cpp_setup_funcdict_BinNormClass();
extern void G__set_cpp_environmentdict_BinNormClass();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BinNormClass.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dict_BinNormClassLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__dict_BinNormClassLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__dict_BinNormClassLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dict_BinNormClassLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_BinNormClassLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__dict_BinNormClassLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgRcLcLiterator;
extern G__linked_taginfo G__dict_BinNormClassLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__dict_BinNormClassLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_BinNormClassLN_BinNormFunctoid;
extern G__linked_taginfo G__dict_BinNormClassLN_maplEintcOBinNormFunctoidmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBinNormFunctoidmUgRsPgRsPgR;
extern G__linked_taginfo G__dict_BinNormClassLN_StartStopStep;
extern G__linked_taginfo G__dict_BinNormClassLN_vectorlEStartStopStepcOallocatorlEStartStopStepgRsPgR;
extern G__linked_taginfo G__dict_BinNormClassLN_reverse_iteratorlEvectorlEStartStopStepcOallocatorlEStartStopStepgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_BinNormClassLN_BinNormClass;
extern G__linked_taginfo G__dict_BinNormClassLN_vectorlEBinNormClasscOallocatorlEBinNormClassgRsPgR;
extern G__linked_taginfo G__dict_BinNormClassLN_vectorlEBinNormClasscOallocatorlEBinNormClassgRsPgRcLcLiterator;
extern G__linked_taginfo G__dict_BinNormClassLN_reverse_iteratorlEvectorlEBinNormClasscOallocatorlEBinNormClassgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_BinNormClassLN_BinNormClasscLcLdA;

/* STUB derived class for protected member access */
