//
// File generated by /cdf/code/cdfsoft/products/root/v5_22_00j-GCC_3_4_6/Linux+2.6/bin/rootcint at Sun Nov  7 18:30:26 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "dict_BinNormFunctoid.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void BinNormFunctoid_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_BinNormFunctoid(void *p = 0);
   static void *newArray_BinNormFunctoid(Long_t size, void *p);
   static void delete_BinNormFunctoid(void *p);
   static void deleteArray_BinNormFunctoid(void *p);
   static void destruct_BinNormFunctoid(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::BinNormFunctoid*)
   {
      ::BinNormFunctoid *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::BinNormFunctoid >(0);
      static ::ROOT::TGenericClassInfo 
         instance("BinNormFunctoid", ::BinNormFunctoid::Class_Version(), "interface/BinNormFunctoid.h", 11,
                  typeid(::BinNormFunctoid), DefineBehavior(ptr, ptr),
                  &::BinNormFunctoid::Dictionary, isa_proxy, 0,
                  sizeof(::BinNormFunctoid) );
      instance.SetNew(&new_BinNormFunctoid);
      instance.SetNewArray(&newArray_BinNormFunctoid);
      instance.SetDelete(&delete_BinNormFunctoid);
      instance.SetDeleteArray(&deleteArray_BinNormFunctoid);
      instance.SetDestructor(&destruct_BinNormFunctoid);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::BinNormFunctoid*)
   {
      return GenerateInitInstanceLocal((::BinNormFunctoid*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::BinNormFunctoid*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *BinNormFunctoid::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *BinNormFunctoid::Class_Name()
{
   return "BinNormFunctoid";
}

//______________________________________________________________________________
const char *BinNormFunctoid::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::BinNormFunctoid*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int BinNormFunctoid::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::BinNormFunctoid*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void BinNormFunctoid::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::BinNormFunctoid*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *BinNormFunctoid::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::BinNormFunctoid*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void BinNormFunctoid::Streamer(TBuffer &R__b)
{
   // Stream an object of class BinNormFunctoid.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b.CheckByteCount(R__s, R__c, BinNormFunctoid::IsA());
   } else {
      R__c = R__b.WriteVersion(BinNormFunctoid::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void BinNormFunctoid::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class BinNormFunctoid.
      TClass *R__cl = ::BinNormFunctoid::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*m_funcPtr", &m_funcPtr);
      TObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_BinNormFunctoid(void *p) {
      return  p ? new(p) ::BinNormFunctoid : new ::BinNormFunctoid;
   }
   static void *newArray_BinNormFunctoid(Long_t nElements, void *p) {
      return p ? new(p) ::BinNormFunctoid[nElements] : new ::BinNormFunctoid[nElements];
   }
   // Wrapper around operator delete
   static void delete_BinNormFunctoid(void *p) {
      delete ((::BinNormFunctoid*)p);
   }
   static void deleteArray_BinNormFunctoid(void *p) {
      delete [] ((::BinNormFunctoid*)p);
   }
   static void destruct_BinNormFunctoid(void *p) {
      typedef ::BinNormFunctoid current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::BinNormFunctoid

/********************************************************
* objects/dict_BinNormFunctoid.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && (__GNUC__ > 3) && (__GNUC_MINOR__ > 1)
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtabledict_BinNormFunctoid();

extern "C" void G__set_cpp_environmentdict_BinNormFunctoid() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("BinNormFunctoid.h");
  G__cpp_reset_tagtabledict_BinNormFunctoid();
}
#include <new>
extern "C" int G__cpp_dllrevdict_BinNormFunctoid() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* BinNormFunctoid */
static int G__dict_BinNormFunctoid_434_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BinNormFunctoid* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BinNormFunctoid[n];
     } else {
       p = new((void*) gvp) BinNormFunctoid[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BinNormFunctoid;
     } else {
       p = new((void*) gvp) BinNormFunctoid;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_BinNormFunctoid));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormFunctoid_434_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BinNormFunctoid* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new BinNormFunctoid((BinNormFunctoid::FuncPtr) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) BinNormFunctoid((BinNormFunctoid::FuncPtr) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_BinNormFunctoid));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormFunctoid_434_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const BinNormFunctoid*) G__getstructoffset())->operator()((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (double) G__double(libp->para[2]), (const double*) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormFunctoid_434_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const BinNormFunctoid*) G__getstructoffset())->dumpToOstream(*(ostream*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormFunctoid_434_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) BinNormFunctoid::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormFunctoid_434_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) BinNormFunctoid::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormFunctoid_434_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) BinNormFunctoid::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormFunctoid_434_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      BinNormFunctoid::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormFunctoid_434_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BinNormFunctoid*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormFunctoid_434_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) BinNormFunctoid::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormFunctoid_434_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) BinNormFunctoid::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormFunctoid_434_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) BinNormFunctoid::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_BinNormFunctoid_434_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) BinNormFunctoid::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__dict_BinNormFunctoid_434_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   BinNormFunctoid* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new BinNormFunctoid(*(BinNormFunctoid*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_BinNormFunctoid));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef BinNormFunctoid G__TBinNormFunctoid;
static int G__dict_BinNormFunctoid_434_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (BinNormFunctoid*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((BinNormFunctoid*) (soff+(sizeof(BinNormFunctoid)*i)))->~G__TBinNormFunctoid();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (BinNormFunctoid*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((BinNormFunctoid*) (soff))->~G__TBinNormFunctoid();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__dict_BinNormFunctoid_434_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BinNormFunctoid* dest = (BinNormFunctoid*) G__getstructoffset();
   *dest = *(BinNormFunctoid*) libp->para[0].ref;
   const BinNormFunctoid& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* BinNormFunctoid */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncdict_BinNormFunctoid {
 public:
  G__Sizep2memfuncdict_BinNormFunctoid(): p(&G__Sizep2memfuncdict_BinNormFunctoid::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncdict_BinNormFunctoid::*p)();
};

size_t G__get_sizep2memfuncdict_BinNormFunctoid()
{
  G__Sizep2memfuncdict_BinNormFunctoid a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancedict_BinNormFunctoid() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_BinNormFunctoid))) {
     BinNormFunctoid *G__Lderived;
     G__Lderived=(BinNormFunctoid*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_BinNormFunctoid),G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetabledict_BinNormFunctoid() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("FuncPtr",89,-1,0,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_BinNormFunctoid));
   G__setnewtype(-1,"double (*FuncPtr) (int tempIndex, int binIndex,",0);
   G__search_typename2("map<int,BinNormFunctoid*>",117,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_maplEintcOBinNormFunctoidmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBinNormFunctoidmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,BinNormFunctoid*,less<int> >",117,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_maplEintcOBinNormFunctoidmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBinNormFunctoidmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("IFMap",117,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_maplEintcOBinNormFunctoidmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBinNormFunctoidmUgRsPgRsPgR),0,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_BinNormFunctoid));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("IFMapConstIter",117,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_maplEintcOBinNormFunctoidmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBinNormFunctoidmUgRsPgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_BinNormFunctoid));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* BinNormFunctoid */
static void G__setup_memvarBinNormFunctoid(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_BinNormFunctoid));
   { BinNormFunctoid *p; p=(BinNormFunctoid*)0x1000; if (p) { }
   G__memvar_setup((void*)0,89,0,0,-1,G__defined_typename("FuncPtr"),-1,4,"m_funcPtr=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvardict_BinNormFunctoid() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncBinNormFunctoid(void) {
   /* BinNormFunctoid */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_BinNormFunctoid));
   G__memfunc_setup("BinNormFunctoid",1521,G__dict_BinNormFunctoid_434_0_1, 105, G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_BinNormFunctoid), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BinNormFunctoid",1521,G__dict_BinNormFunctoid_434_0_2, 105, G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_BinNormFunctoid), -1, 0, 1, 1, 1, 0, "Y - 'BinNormFunctoid::FuncPtr' 0 - ptr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator()",957,G__dict_BinNormFunctoid_434_0_3, 100, -1, -1, 0, 4, 1, 1, 8, 
"i - - 0 - tempIndex i - - 0 - binIndex "
"d - - 0 - value D - - 10 - paramArray", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("dumpToOstream",1364,G__dict_BinNormFunctoid_434_0_4, 121, -1, -1, 0, 1, 1, 1, 8, "u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - o_stream", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__dict_BinNormFunctoid_434_0_5, 85, G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (TClass* (*)())(&BinNormFunctoid::Class), 0);
   G__memfunc_setup("Class_Name",982,G__dict_BinNormFunctoid_434_0_6, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&BinNormFunctoid::Class_Name), 0);
   G__memfunc_setup("Class_Version",1339,G__dict_BinNormFunctoid_434_0_7, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (Version_t (*)())(&BinNormFunctoid::Class_Version), 0);
   G__memfunc_setup("Dictionary",1046,G__dict_BinNormFunctoid_434_0_8, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (void (*)())(&BinNormFunctoid::Dictionary), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__dict_BinNormFunctoid_434_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__dict_BinNormFunctoid_434_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&BinNormFunctoid::DeclFileName), 0);
   G__memfunc_setup("ImplFileLine",1178,G__dict_BinNormFunctoid_434_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&BinNormFunctoid::ImplFileLine), 0);
   G__memfunc_setup("ImplFileName",1171,G__dict_BinNormFunctoid_434_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&BinNormFunctoid::ImplFileName), 0);
   G__memfunc_setup("DeclFileLine",1152,G__dict_BinNormFunctoid_434_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&BinNormFunctoid::DeclFileLine), 0);
   // automatic copy constructor
   G__memfunc_setup("BinNormFunctoid", 1521, G__dict_BinNormFunctoid_434_0_17, (int) ('i'), G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_BinNormFunctoid), -1, 0, 1, 1, 1, 0, "u 'BinNormFunctoid' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BinNormFunctoid", 1647, G__dict_BinNormFunctoid_434_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__dict_BinNormFunctoid_434_0_19, (int) ('u'), G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_BinNormFunctoid), -1, 1, 1, 1, 1, 0, "u 'BinNormFunctoid' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncdict_BinNormFunctoid() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaldict_BinNormFunctoid() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcdict_BinNormFunctoid() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__dict_BinNormFunctoidLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__dict_BinNormFunctoidLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__dict_BinNormFunctoidLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__dict_BinNormFunctoidLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__dict_BinNormFunctoidLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__dict_BinNormFunctoidLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR = { "basic_ostream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G__dict_BinNormFunctoidLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__dict_BinNormFunctoidLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_BinNormFunctoidLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__dict_BinNormFunctoidLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_BinNormFunctoidLN_BinNormFunctoid = { "BinNormFunctoid" , 99 , -1 };
G__linked_taginfo G__dict_BinNormFunctoidLN_maplEintcOBinNormFunctoidmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBinNormFunctoidmUgRsPgRsPgR = { "map<int,BinNormFunctoid*,less<int>,allocator<pair<const int,BinNormFunctoid*> > >" , 99 , -1 };
G__linked_taginfo G__dict_BinNormFunctoidLN_maplEintcOBinNormFunctoidmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBinNormFunctoidmUgRsPgRsPgRcLcLiterator = { "map<int,BinNormFunctoid*,less<int>,allocator<pair<const int,BinNormFunctoid*> > >::iterator" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtabledict_BinNormFunctoid() {
  G__dict_BinNormFunctoidLN_TClass.tagnum = -1 ;
  G__dict_BinNormFunctoidLN_TBuffer.tagnum = -1 ;
  G__dict_BinNormFunctoidLN_TMemberInspector.tagnum = -1 ;
  G__dict_BinNormFunctoidLN_TObject.tagnum = -1 ;
  G__dict_BinNormFunctoidLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__dict_BinNormFunctoidLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G__dict_BinNormFunctoidLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__dict_BinNormFunctoidLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_BinNormFunctoidLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__dict_BinNormFunctoidLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_BinNormFunctoidLN_BinNormFunctoid.tagnum = -1 ;
  G__dict_BinNormFunctoidLN_maplEintcOBinNormFunctoidmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBinNormFunctoidmUgRsPgRsPgR.tagnum = -1 ;
  G__dict_BinNormFunctoidLN_maplEintcOBinNormFunctoidmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBinNormFunctoidmUgRsPgRsPgRcLcLiterator.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtabledict_BinNormFunctoid() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__dict_BinNormFunctoidLN_TClass);
   G__get_linked_tagnum_fwd(&G__dict_BinNormFunctoidLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__dict_BinNormFunctoidLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__dict_BinNormFunctoidLN_TObject);
   G__get_linked_tagnum_fwd(&G__dict_BinNormFunctoidLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_BinNormFunctoidLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_BinNormFunctoidLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_BinNormFunctoidLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dict_BinNormFunctoidLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_BinNormFunctoidLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__dict_BinNormFunctoidLN_BinNormFunctoid),sizeof(BinNormFunctoid),-1,61696,"BinNormFunctoid Class",G__setup_memvarBinNormFunctoid,G__setup_memfuncBinNormFunctoid);
   G__get_linked_tagnum_fwd(&G__dict_BinNormFunctoidLN_maplEintcOBinNormFunctoidmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBinNormFunctoidmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_BinNormFunctoidLN_maplEintcOBinNormFunctoidmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOBinNormFunctoidmUgRsPgRsPgRcLcLiterator);
}
extern "C" void G__cpp_setupdict_BinNormFunctoid(void) {
  G__check_setup_version(30051515,"G__cpp_setupdict_BinNormFunctoid()");
  G__set_cpp_environmentdict_BinNormFunctoid();
  G__cpp_setup_tagtabledict_BinNormFunctoid();

  G__cpp_setup_inheritancedict_BinNormFunctoid();

  G__cpp_setup_typetabledict_BinNormFunctoid();

  G__cpp_setup_memvardict_BinNormFunctoid();

  G__cpp_setup_memfuncdict_BinNormFunctoid();
  G__cpp_setup_globaldict_BinNormFunctoid();
  G__cpp_setup_funcdict_BinNormFunctoid();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncdict_BinNormFunctoid();
  return;
}
class G__cpp_setup_initdict_BinNormFunctoid {
  public:
    G__cpp_setup_initdict_BinNormFunctoid() { G__add_setup_func("dict_BinNormFunctoid",(G__incsetup)(&G__cpp_setupdict_BinNormFunctoid)); G__call_setup_funcs(); }
   ~G__cpp_setup_initdict_BinNormFunctoid() { G__remove_setup_func("dict_BinNormFunctoid"); }
};
G__cpp_setup_initdict_BinNormFunctoid G__cpp_setup_initializerdict_BinNormFunctoid;

