# SoftRelTools GNUmakefile for KinematicFitter top level

# Compile the files in src subdirectory
SUBDIRS=dict src test

# Header files go in include subdirectory
PACKAGE_INCLUDE=KinematicFitter

################################
include SoftRelTools/standard.mk
