#!/usr/bin/perl

use strict;
use warnings;

my $prefix = shift || "";

my @files = glob ("$prefix*.gif");

die unless @files;

my $factor = 100;
if ($files[$#files - 1] =~ /0*(\d+)\D+$/) {
    if (length ($1) >= 3) {
        $factor = 1000;
    }
}
    
print "<html><title>$prefix Distributions</title>\n";

foreach my $file (@files) {
    (my $eps = $file ) =~ s/gif/eps/;
    my $b;
    if ($file =~ /0?(\d+)\D*$/) {
        $b = $1 / $factor;
    } else {
        next;
    }
    print "<hr><h2>b = $b</h2>\n<a href=\"$eps\"><img src=\"$file\"></a><br><br>\n";
}

