#!/usr/bin/perl -w
$flag = "%";

$newcommand = shift @ARGV;
while ($newcommand =~ /^-/) {
    $arg = $newcommand;
    $newcommand = shift @ARGV;
    # silent
    if ($arg =~ /^-s/) {
        $silent = "true";
        next;
    }
}

if (!@ARGV) {
	$prog = $0;
	$prog =~ s|.*/||g;
	print qq(Usage: $prog command file1 file2 ...
Use '$flag' instead of the filename.
ex:
$prog "mv $flag ../bin/#.old" file1 file2 file3... );
	die "\n";
}

foreach $file (@ARGV) {
    if (! open(SOURCE, $file)) {
        warn "Can't open $file\n";
        next;
    }
    while ($line = <SOURCE>) {
        ++$count;
        $command = $newcommand;
        chomp $line;
        $command =~ s/$flag/$line/g;
        if ($silent) {
            system "$command";
            print "count $count\n" if (0 == $count%100);
        } else {
            print "unix> $command\n";
            print `$command`;
            print "\n";
        }
    }
}
