#!/bin/sh
echo b0pcucla09\> $1 $2 $3 $4 $5 $6 $7 $8 $9
ssh  b0pcucla09   $1 $2 $3 $4 $5 $6 $7 $8 $9
echo
echo b0pcucla10\> $1 $2 $3 $4 $5 $6 $7 $8 $9
ssh  b0pcucla10   $1 $2 $3 $4 $5 $6 $7 $8 $9
echo
echo b0pcucla11\> $1 $2 $3 $4 $5 $6 $7 $8 $9
ssh  b0pcucla11   $1 $2 $3 $4 $5 $6 $7 $8 $9
echo
echo b0pcucla12\> $1 $2 $3 $4 $5 $6 $7 $8 $9
ssh  b0pcucla12   $1 $2 $3 $4 $5 $6 $7 $8 $9
echo
echo b0pcucla13\> $1 $2 $3 $4 $5 $6 $7 $8 $9
ssh  b0pcucla13   $1 $2 $3 $4 $5 $6 $7 $8 $9
echo
echo b0pcucla20\> $1 $2 $3 $4 $5 $6 $7 $8 $9
ssh  b0pcucla20   $1 $2 $3 $4 $5 $6 $7 $8 $9
echo
echo b0pcucla21\> $1 $2 $3 $4 $5 $6 $7 $8 $9
ssh  b0pcucla21   $1 $2 $3 $4 $5 $6 $7 $8 $9
echo
