#!/usr/bin/env perl

use Tk;

$startcommand = "/cdf/home/cplager/bin/startcommand";
$xterm = "/usr/bin/X11/rxvt";
$checkKerberos = "/cdf/home/cplager/bin/checkKerberos";

$main = MainWindow->new(-bg => 'white',
						-fg => 'black',
						title => "Kerberos Ticket Status");
$value = `$checkKerberos`;
chomp $value;
$label = $main->Label(-text => $value)->pack(-side => 'top');
$quitButton = $main->Button(-text => "OK",
						  -relief => 'flat',
						  -borderwidth => 2,
						  -width => 4,
						  -takefocus => 1,
						  -highlightthickness => 3,
						  -background => 'white',
						  -foreground => 'black',
 						  -activebackground => 'white',
						  -activeforeground => 'red',
						  -command => \&quit)->
	pack (-side => 'bottom',
		  -anchor => 'center',
		  -padx => 5,
		  -pady => 5);
$kinitButton = $main->Button(-text => "Get new ticket",
						  -relief => 'flat',
						  -borderwidth => 2,
						  -highlightthickness => 3,
						  -background => 'white',
						  -foreground => 'black',
 						  -activebackground => 'white',
						  -activeforeground => 'red',
						  -command => \&kinit)->
	pack (-side => 'bottom',
		  -anchor => 'center',
		  -padx => 5,
		  -pady => 5);
if ($value =~ /will/) {
    $quitButton->focus();
    $main->bind ('<Return>', \&quit);
    $main->bind ('<KP_Enter>', \&quit);
} else {
    $kinitButton->focus();
    $main->bind ('<Return>', \&kinit);
    $main->bind ('<KP_Enter>', \&kinit);
}
MainLoop;

sub kinit {
    $command = "$startcommand $xterm -title 'kinit' -fn 6x13 -fg white -bg black -e \"kinit -l 100d;$0\" ";
    system $command;
    exit;
}

sub quit {
	exit;
}
