#!/usr/bin/env perl
#root        597   0  0.0     0:00.05 dtlogin <:0> -daemon
#cplager  12299   0  0.0 00:00:00 ps -A -o user -o pid -o nice -o pcpu -o cpu
#0123456789012345678901234567890123456789012345678901234567890
#          1         2         3         4   
$wait = 5;
$cpulimit = 25;

if (@ARGV) {
	if ($ARGV[0] =~ /(\d+)/) {
		if ($1 > 0) {
			$wait = $1;
		}
	}
}
open (PROCESS, "ps -A -o user -o pid -o nice -o pcpu -o cputime -o command|") 
	or die ("Couldn't get list");
$first = -1;
while ($line = <PROCESS>) {
	$command = substr ($line, 33);   #gets command
	chop $command;
	$time = substr ($line, 24, 9);  #gets CPU time
	($user) = ($line =~ /(^\w+)\s/); #sets username
	( $number, $niceness, $percent) = ( $line =~ /\s*(\d+)\s+(-?\d+)\s+(\d+)\./ ); #gets pid
	$hours = 0;
	$minutes = 0;
	if ($time =~ /(\d+):\d{2}\.\d{1,2}/) {
		$minutes = $1; #gets time in format mm:ss.h(h)
	} elsif ($time =~ /(\d+):(\d+):\d+/) {
		$hours = $1;   #gets time in format hh:mm:ss
		$minutes = $2;
	}
	$total = $hours * 60 + $minutes; #number of CPU minutes used
	if ( (($percent > $cpulimit) || ($total >= $wait)) 
        && ($user !~ /^root$/)) {
		if ($first) {
			$first = 0;
			print "     USER  : TIME :   PID  NICE  CPU  COMMAND\n";
		}
		printf ("%-10s : %4s : %6s %4s  %2s%%  %s\n", $user, $total, $number, $niceness, $percent, $command);
	}
}



