#!/usr/bin/perl
$filename = shift @ARGV;
$template = "/cdf//home/cplager/code/sample";
die "Usage: $0 HeaderFileNmae\n" unless ($filename);
$filename =~ s/\.h$//i;
$filename =~ s/\.cc$//i;
($short = $filename) =~ s|.*/||g;

if (-e "$filename.h" || -e "$filename.cc") {
    die "$filename.h or $filename.cc already exists.\nExiting...\n";
}

system "perl -pe 's/sample/$short/ig' $template.h > $filename.h";
system "perl -pe 's/sample/$short/ig' $template.cc > $filename.cc";
