#!/usr/bin/env perl

use YourNeverGonnaFindThis;

die "Usage: $0 command (seconds)\n" unless (@ARGV);
if (@ARGV >= 2) {
	$seconds = $ARGV[1];
} else {
	$seconds = 1;
}

while (1) {
	system "clear";
	print "unix> $ARGV[0]\n";
	print `$ARGV[0]`;
	sleep $seconds;
}
