/********************************************************************
* objects/dict_CLPFunctionoid2Slide.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error objects/dict_CLPFunctionoid2Slide.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtabledict_CLPFunctionoid2Slide();
extern void G__cpp_setup_inheritancedict_CLPFunctionoid2Slide();
extern void G__cpp_setup_typetabledict_CLPFunctionoid2Slide();
extern void G__cpp_setup_memvardict_CLPFunctionoid2Slide();
extern void G__cpp_setup_globaldict_CLPFunctionoid2Slide();
extern void G__cpp_setup_memfuncdict_CLPFunctionoid2Slide();
extern void G__cpp_setup_funcdict_CLPFunctionoid2Slide();
extern void G__set_cpp_environmentdict_CLPFunctionoid2Slide();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "CLPFunctionoid2Slide.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dict_CLPFunctionoid2SlideLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__dict_CLPFunctionoid2SlideLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dict_CLPFunctionoid2SlideLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_CLPFunctionoid2SlideLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__dict_CLPFunctionoid2SlideLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_CLPFunctionoid2SlideLN_CLPFunctionoid2;
extern G__linked_taginfo G__dict_CLPFunctionoid2SlideLN_CLPFunctionoid2Slide;

/* STUB derived class for protected member access */
