//
// File generated by /cdf/code/cdfsoft/products/root/v5_22_00j-GCC_3_4_6/Linux+2.6/bin/rootcint at Sun Nov  7 18:30:21 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "dict_CLPBinCont.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void CLPBinCont_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_CLPBinCont(void *p = 0);
   static void *newArray_CLPBinCont(Long_t size, void *p);
   static void delete_CLPBinCont(void *p);
   static void deleteArray_CLPBinCont(void *p);
   static void destruct_CLPBinCont(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::CLPBinCont*)
   {
      ::CLPBinCont *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::CLPBinCont >(0);
      static ::ROOT::TGenericClassInfo 
         instance("CLPBinCont", ::CLPBinCont::Class_Version(), "interface/CLPBinCont.h", 16,
                  typeid(::CLPBinCont), DefineBehavior(ptr, ptr),
                  &::CLPBinCont::Dictionary, isa_proxy, 0,
                  sizeof(::CLPBinCont) );
      instance.SetNew(&new_CLPBinCont);
      instance.SetNewArray(&newArray_CLPBinCont);
      instance.SetDelete(&delete_CLPBinCont);
      instance.SetDeleteArray(&deleteArray_CLPBinCont);
      instance.SetDestructor(&destruct_CLPBinCont);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::CLPBinCont*)
   {
      return GenerateInitInstanceLocal((::CLPBinCont*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::CLPBinCont*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *CLPBinCont::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *CLPBinCont::Class_Name()
{
   return "CLPBinCont";
}

//______________________________________________________________________________
const char *CLPBinCont::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CLPBinCont*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int CLPBinCont::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CLPBinCont*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void CLPBinCont::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CLPBinCont*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *CLPBinCont::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CLPBinCont*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void CLPBinCont::Streamer(TBuffer &R__b)
{
   // Stream an object of class CLPBinCont.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      {
         CLPBin::Vec &R__stl =  m_vec;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            CLPBin R__t;
            R__t.Streamer(R__b);
            R__stl.push_back(R__t);
         }
      }
      R__b >> m_integral;
      R__b >> m_noOverflow;
      R__b >> m_dontRemovePoints;
      R__b >> m_debug;
      R__b.CheckByteCount(R__s, R__c, CLPBinCont::IsA());
   } else {
      R__c = R__b.WriteVersion(CLPBinCont::IsA(), kTRUE);
      TObject::Streamer(R__b);
      {
         CLPBin::Vec &R__stl =  m_vec;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            CLPBin::Vec::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            ((CLPBin&)(*R__k)).Streamer(R__b);
            }
         }
      }
      R__b << m_integral;
      R__b << m_noOverflow;
      R__b << m_dontRemovePoints;
      R__b << m_debug;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void CLPBinCont::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class CLPBinCont.
      TClass *R__cl = ::CLPBinCont::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "m_vec", (void*)&m_vec);
      ::ROOT::GenericShowMembers("CLPBin::Vec", (void*)&m_vec, R__insp, strcat(R__parent,"m_vec."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "m_integral", &m_integral);
      R__insp.Inspect(R__cl, R__parent, "m_noOverflow", &m_noOverflow);
      R__insp.Inspect(R__cl, R__parent, "m_dontRemovePoints", &m_dontRemovePoints);
      R__insp.Inspect(R__cl, R__parent, "m_debug", &m_debug);
      TObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_CLPBinCont(void *p) {
      return  p ? new(p) ::CLPBinCont : new ::CLPBinCont;
   }
   static void *newArray_CLPBinCont(Long_t nElements, void *p) {
      return p ? new(p) ::CLPBinCont[nElements] : new ::CLPBinCont[nElements];
   }
   // Wrapper around operator delete
   static void delete_CLPBinCont(void *p) {
      delete ((::CLPBinCont*)p);
   }
   static void deleteArray_CLPBinCont(void *p) {
      delete [] ((::CLPBinCont*)p);
   }
   static void destruct_CLPBinCont(void *p) {
      typedef ::CLPBinCont current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::CLPBinCont

namespace ROOT {
   void vectorlECLPBingR_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void vectorlECLPBingR_Dictionary();
   static void *new_vectorlECLPBingR(void *p = 0);
   static void *newArray_vectorlECLPBingR(Long_t size, void *p);
   static void delete_vectorlECLPBingR(void *p);
   static void deleteArray_vectorlECLPBingR(void *p);
   static void destruct_vectorlECLPBingR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<CLPBin>*)
   {
      vector<CLPBin> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<CLPBin>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<CLPBin>", -2, "prec_stl/vector", 49,
                  typeid(vector<CLPBin>), DefineBehavior(ptr, ptr),
                  0, &vectorlECLPBingR_Dictionary, isa_proxy, 0,
                  sizeof(vector<CLPBin>) );
      instance.SetNew(&new_vectorlECLPBingR);
      instance.SetNewArray(&newArray_vectorlECLPBingR);
      instance.SetDelete(&delete_vectorlECLPBingR);
      instance.SetDeleteArray(&deleteArray_vectorlECLPBingR);
      instance.SetDestructor(&destruct_vectorlECLPBingR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<CLPBin> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<CLPBin>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlECLPBingR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<CLPBin>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlECLPBingR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<CLPBin> : new vector<CLPBin>;
   }
   static void *newArray_vectorlECLPBingR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<CLPBin>[nElements] : new vector<CLPBin>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlECLPBingR(void *p) {
      delete ((vector<CLPBin>*)p);
   }
   static void deleteArray_vectorlECLPBingR(void *p) {
      delete [] ((vector<CLPBin>*)p);
   }
   static void destruct_vectorlECLPBingR(void *p) {
      typedef vector<CLPBin> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<CLPBin>

/********************************************************
* objects/dict_CLPBinCont.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && (__GNUC__ > 3) && (__GNUC_MINOR__ > 1)
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtabledict_CLPBinCont();

extern "C" void G__set_cpp_environmentdict_CLPBinCont() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("CLPBinCont.h");
  G__cpp_reset_tagtabledict_CLPBinCont();
}
#include <new>
extern "C" int G__cpp_dllrevdict_CLPBinCont() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* CLPBinCont */
static int G__dict_CLPBinCont_472_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CLPBinCont* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CLPBinCont[n];
     } else {
       p = new((void*) gvp) CLPBinCont[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CLPBinCont;
     } else {
       p = new((void*) gvp) CLPBinCont;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_CLPBinContLN_CLPBinCont));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CLPBinCont* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new CLPBinCont((TH1F*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) CLPBinCont((TH1F*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_CLPBinContLN_CLPBinCont));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPBinCont*) G__getstructoffset())->clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const CLPBinCont*) G__getstructoffset())->integral());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const CLPBinCont*) G__getstructoffset())->size());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const CLPBinCont*) G__getstructoffset())->dontRemovePoints());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPBinCont*) G__getstructoffset())->setDontRemovePoints((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      CLPBinCont::setDontRemovePointsDefault((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPBinCont*) G__getstructoffset())->integrateTH1F((TH1F*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPBinCont*) G__getstructoffset())->addBin((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (bool) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPBinCont*) G__getstructoffset())->addBin((double) G__double(libp->para[0]), (double) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPBinCont*) G__getstructoffset())->addBinCarefully((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((const CLPBinCont*) G__getstructoffset())->fillTH1F((TH1F*) G__int(libp->para[0]), (bool) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((const CLPBinCont*) G__getstructoffset())->fillTH1F((TH1F*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const CLPBinCont*) G__getstructoffset())->tgraphPtr());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const CLPBinCont*) G__getstructoffset())->moveIterators(*(CLPBin::VecConstIter*) libp->para[0].ref, *(CLPBin::VecConstIter*) libp->para[1].ref
, (double) G__double(libp->para[2]), *(double*) G__Doubleref(&libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPBinCont*) G__getstructoffset())->horizontalMorph(*(CLPBinCont*) libp->para[0].ref, *(CLPBinCont*) libp->para[1].ref
, (double) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPBinCont*) G__getstructoffset())->horizontalSubtract(*(CLPBinCont*) libp->para[0].ref, *(CLPBinCont*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPBinCont*) G__getstructoffset())->horizontalDeltaMorph(*(CLPBinCont*) libp->para[0].ref, *(CLPBinCont*) libp->para[1].ref
, (double) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPBinCont*) G__getstructoffset())->horizontalFunction(*(CLPBinCont*) libp->para[0].ref, *(CLPBinCont*) libp->para[1].ref
, *(CLPFunctionoid2*) libp->para[2].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      ((CLPBinCont*) G__getstructoffset())->horizontalAdd(*(CLPBinCont*) libp->para[0].ref, *(CLPBinCont*) libp->para[1].ref
, (double) G__double(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ((CLPBinCont*) G__getstructoffset())->horizontalAdd(*(CLPBinCont*) libp->para[0].ref, *(CLPBinCont*) libp->para[1].ref);
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((CLPBinCont*) G__getstructoffset())->smoothBeginningOfDelta((double) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((CLPBinCont*) G__getstructoffset())->smoothBeginningOfDelta();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) CLPBinCont::percentInBetween((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) CLPBinCont::areTheSame((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) CLPBinCont::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CLPBinCont::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) CLPBinCont::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      CLPBinCont::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPBinCont*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CLPBinCont::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CLPBinCont::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CLPBinCont::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPBinCont_472_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CLPBinCont::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__dict_CLPBinCont_472_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   CLPBinCont* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new CLPBinCont(*(CLPBinCont*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_CLPBinContLN_CLPBinCont));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef CLPBinCont G__TCLPBinCont;
static int G__dict_CLPBinCont_472_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (CLPBinCont*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((CLPBinCont*) (soff+(sizeof(CLPBinCont)*i)))->~G__TCLPBinCont();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (CLPBinCont*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((CLPBinCont*) (soff))->~G__TCLPBinCont();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__dict_CLPBinCont_472_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CLPBinCont* dest = (CLPBinCont*) G__getstructoffset();
   *dest = *(CLPBinCont*) libp->para[0].ref;
   const CLPBinCont& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* CLPBinCont */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncdict_CLPBinCont {
 public:
  G__Sizep2memfuncdict_CLPBinCont(): p(&G__Sizep2memfuncdict_CLPBinCont::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncdict_CLPBinCont::*p)();
};

size_t G__get_sizep2memfuncdict_CLPBinCont()
{
  G__Sizep2memfuncdict_CLPBinCont a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancedict_CLPBinCont() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__dict_CLPBinContLN_CLPBinCont))) {
     CLPBinCont *G__Lderived;
     G__Lderived=(CLPBinCont*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dict_CLPBinContLN_CLPBinCont),G__get_linked_tagnum(&G__dict_CLPBinContLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetabledict_CLPBinCont() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPBinContLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPBinContLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPBinContLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPBinContLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<CLPBin>",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_vectorlECLPBincOallocatorlECLPBingRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_reverse_iteratorlEvectorlECLPBincOallocatorlECLPBingRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPBinContLN_vectorlECLPBincOallocatorlECLPBingRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_reverse_iteratorlEvectorlECLPBincOallocatorlECLPBingRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPBinContLN_vectorlECLPBincOallocatorlECLPBingRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<double,CLPBinCont>",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_maplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<double,CLPBinCont,less<double> >",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_maplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("DMap",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_maplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgR),0,G__get_linked_tagnum(&G__dict_CLPBinContLN_CLPBinCont));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("DMapConstIter",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_maplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_CLPBinContLN_CLPBinCont));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<DMap>",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_reverse_iteratorlEvectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPBinContLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_reverse_iteratorlEvectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPBinContLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > > >",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("DMapVec",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgR),0,G__get_linked_tagnum(&G__dict_CLPBinContLN_CLPBinCont));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("DMapVecConstIter",117,G__get_linked_tagnum(&G__dict_CLPBinContLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_CLPBinContLN_CLPBinCont));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* CLPBinCont */
static void G__setup_memvarCLPBinCont(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__dict_CLPBinContLN_CLPBinCont));
   { CLPBinCont *p; p=(CLPBinCont*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__dict_CLPBinContLN_vectorlECLPBincOallocatorlECLPBingRsPgR),G__defined_typename("Vec"),-1,4,"m_vec=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"m_integral=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_noOverflow=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_dontRemovePoints=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_debug=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-2,4,"sm_dontRemovePointsDefault=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dict_CLPBinContLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvardict_CLPBinCont() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncCLPBinCont(void) {
   /* CLPBinCont */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__dict_CLPBinContLN_CLPBinCont));
   G__memfunc_setup("CLPBinCont",908,G__dict_CLPBinCont_472_0_1, 105, G__get_linked_tagnum(&G__dict_CLPBinContLN_CLPBinCont), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CLPBinCont",908,G__dict_CLPBinCont_472_0_2, 105, G__get_linked_tagnum(&G__dict_CLPBinContLN_CLPBinCont), -1, 0, 1, 1, 1, 0, "U 'TH1F' - 0 - histPtr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("clear",519,G__dict_CLPBinCont_472_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("integral",854,G__dict_CLPBinCont_472_0_4, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("size",443,G__dict_CLPBinCont_472_0_5, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("dontRemovePoints",1696,G__dict_CLPBinCont_472_0_6, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setDontRemovePoints",1996,G__dict_CLPBinCont_472_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - dontRemovePoints", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setDontRemovePointsDefault",2705,G__dict_CLPBinCont_472_0_8, 121, -1, -1, 0, 1, 3, 1, 0, "g - - 0 - dontRemoveDefault", (char*)NULL, (void*) (void (*)(bool))(&CLPBinCont::setDontRemovePointsDefault), 0);
   G__memfunc_setup("integrateTH1F",1238,G__dict_CLPBinCont_472_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TH1F' - 0 - histPtr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addBin",578,G__dict_CLPBinCont_472_0_10, 121, -1, -1, 0, 4, 1, 1, 0, 
"d - - 0 - low d - - 0 - width "
"d - - 0 - total g - - 0 - isZero", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addBin",578,G__dict_CLPBinCont_472_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - upper d - - 0 - total", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addBinCarefully",1513,G__dict_CLPBinCont_472_0_12, 121, -1, -1, 0, 3, 1, 1, 0, 
"d - - 0 - low d - - 0 - width "
"d - - 0 - total", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("fillTH1F",698,G__dict_CLPBinCont_472_0_13, 121, -1, -1, 0, 2, 1, 1, 8, 
"U 'TH1F' - 0 - histPtr g - - 0 'false' noUnderOverFlow", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("tgraphPtr",956,G__dict_CLPBinCont_472_0_14, 85, G__get_linked_tagnum(&G__dict_CLPBinContLN_TGraph), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("moveIterators",1396,G__dict_CLPBinCont_472_0_15, 103, -1, -1, 0, 4, 1, 1, 8, 
"u 'vector<CLPBin,allocator<CLPBin> >::iterator' 'CLPBin::VecConstIter' 1 - lowerIter u 'vector<CLPBin,allocator<CLPBin> >::iterator' 'CLPBin::VecConstIter' 1 - upperIter "
"d - - 0 - xValue d - - 1 - yValue", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("horizontalMorph",1616,G__dict_CLPBinCont_472_0_16, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'CLPBinCont' - 11 - alpha u 'CLPBinCont' - 11 - beta "
"d - - 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("horizontalSubtract",1938,G__dict_CLPBinCont_472_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'CLPBinCont' - 11 - alpha u 'CLPBinCont' - 11 - beta", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("horizontalDeltaMorph",2106,G__dict_CLPBinCont_472_0_18, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'CLPBinCont' - 11 - alpha u 'CLPBinCont' - 11 - beta "
"d - - 0 - percentage", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("horizontalFunction",1936,G__dict_CLPBinCont_472_0_19, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'CLPBinCont' - 11 - alpha u 'CLPBinCont' - 11 - beta "
"u 'CLPFunctionoid2' - 11 - functionoid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("horizontalAdd",1363,G__dict_CLPBinCont_472_0_20, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'CLPBinCont' - 11 - alpha u 'CLPBinCont' - 11 - delta "
"d - - 0 '1.' percentage", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("smoothBeginningOfDelta",2250,G__dict_CLPBinCont_472_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 '0.05' percentStep", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("percentInBetween",1650,G__dict_CLPBinCont_472_0_22, 100, -1, -1, 0, 3, 3, 1, 0, 
"d - - 0 - alpha d - - 0 - beta "
"d - - 0 - param", (char*)NULL, (void*) (double (*)(double, double, double))(&CLPBinCont::percentInBetween), 0);
   G__memfunc_setup("areTheSame",991,G__dict_CLPBinCont_472_0_23, 103, -1, -1, 0, 2, 3, 1, 0, 
"d - - 0 - alpha d - - 0 - beta", (char*)NULL, (void*) (bool (*)(double, double))(&CLPBinCont::areTheSame), 0);
   G__memfunc_setup("Class",502,G__dict_CLPBinCont_472_0_24, 85, G__get_linked_tagnum(&G__dict_CLPBinContLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (TClass* (*)())(&CLPBinCont::Class), 0);
   G__memfunc_setup("Class_Name",982,G__dict_CLPBinCont_472_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&CLPBinCont::Class_Name), 0);
   G__memfunc_setup("Class_Version",1339,G__dict_CLPBinCont_472_0_26, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (Version_t (*)())(&CLPBinCont::Class_Version), 0);
   G__memfunc_setup("Dictionary",1046,G__dict_CLPBinCont_472_0_27, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (void (*)())(&CLPBinCont::Dictionary), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__dict_CLPBinContLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__dict_CLPBinCont_472_0_31, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__dict_CLPBinCont_472_0_32, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&CLPBinCont::DeclFileName), 0);
   G__memfunc_setup("ImplFileLine",1178,G__dict_CLPBinCont_472_0_33, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&CLPBinCont::ImplFileLine), 0);
   G__memfunc_setup("ImplFileName",1171,G__dict_CLPBinCont_472_0_34, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&CLPBinCont::ImplFileName), 0);
   G__memfunc_setup("DeclFileLine",1152,G__dict_CLPBinCont_472_0_35, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&CLPBinCont::DeclFileLine), 0);
   // automatic copy constructor
   G__memfunc_setup("CLPBinCont", 908, G__dict_CLPBinCont_472_0_36, (int) ('i'), G__get_linked_tagnum(&G__dict_CLPBinContLN_CLPBinCont), -1, 0, 1, 1, 1, 0, "u 'CLPBinCont' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~CLPBinCont", 1034, G__dict_CLPBinCont_472_0_37, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__dict_CLPBinCont_472_0_38, (int) ('u'), G__get_linked_tagnum(&G__dict_CLPBinContLN_CLPBinCont), -1, 1, 1, 1, 1, 0, "u 'CLPBinCont' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncdict_CLPBinCont() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaldict_CLPBinCont() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcdict_CLPBinCont() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__dict_CLPBinContLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_TH1F = { "TH1F" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_TGraph = { "TGraph" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_vectorlECLPBincOallocatorlECLPBingRsPgR = { "vector<CLPBin,allocator<CLPBin> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_vectorlECLPBincOallocatorlECLPBingRsPgRcLcLiterator = { "vector<CLPBin,allocator<CLPBin> >::iterator" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_reverse_iteratorlEvectorlECLPBincOallocatorlECLPBingRsPgRcLcLiteratorgR = { "reverse_iterator<vector<CLPBin,allocator<CLPBin> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_CLPFunctionoid2 = { "CLPFunctionoid2" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_CLPBinCont = { "CLPBinCont" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_maplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgR = { "map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > >" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_maplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcLcLiterator = { "map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > >::iterator" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgR = { "vector<map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > >,allocator<map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > > > >" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgRcLcLiterator = { "vector<map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > >,allocator<map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > > > >::iterator" , 99 , -1 };
G__linked_taginfo G__dict_CLPBinContLN_reverse_iteratorlEvectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > >,allocator<map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > > > >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtabledict_CLPBinCont() {
  G__dict_CLPBinContLN_TClass.tagnum = -1 ;
  G__dict_CLPBinContLN_TBuffer.tagnum = -1 ;
  G__dict_CLPBinContLN_TMemberInspector.tagnum = -1 ;
  G__dict_CLPBinContLN_TObject.tagnum = -1 ;
  G__dict_CLPBinContLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__dict_CLPBinContLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__dict_CLPBinContLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_CLPBinContLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__dict_CLPBinContLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_CLPBinContLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__dict_CLPBinContLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__dict_CLPBinContLN_TH1F.tagnum = -1 ;
  G__dict_CLPBinContLN_TGraph.tagnum = -1 ;
  G__dict_CLPBinContLN_vectorlECLPBincOallocatorlECLPBingRsPgR.tagnum = -1 ;
  G__dict_CLPBinContLN_vectorlECLPBincOallocatorlECLPBingRsPgRcLcLiterator.tagnum = -1 ;
  G__dict_CLPBinContLN_reverse_iteratorlEvectorlECLPBincOallocatorlECLPBingRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_CLPBinContLN_CLPFunctionoid2.tagnum = -1 ;
  G__dict_CLPBinContLN_CLPBinCont.tagnum = -1 ;
  G__dict_CLPBinContLN_maplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgR.tagnum = -1 ;
  G__dict_CLPBinContLN_maplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcLcLiterator.tagnum = -1 ;
  G__dict_CLPBinContLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__dict_CLPBinContLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgRcLcLiterator.tagnum = -1 ;
  G__dict_CLPBinContLN_reverse_iteratorlEvectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtabledict_CLPBinCont() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_TClass);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_TObject);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_TH1F);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_TGraph);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_vectorlECLPBincOallocatorlECLPBingRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_vectorlECLPBincOallocatorlECLPBingRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_reverse_iteratorlEvectorlECLPBincOallocatorlECLPBingRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_CLPFunctionoid2);
   G__tagtable_setup(G__get_linked_tagnum(&G__dict_CLPBinContLN_CLPBinCont),sizeof(CLPBinCont),-1,61696,"CLPBinCont Class",G__setup_memvarCLPBinCont,G__setup_memfuncCLPBinCont);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_maplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_maplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G__dict_CLPBinContLN_reverse_iteratorlEvectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupdict_CLPBinCont(void) {
  G__check_setup_version(30051515,"G__cpp_setupdict_CLPBinCont()");
  G__set_cpp_environmentdict_CLPBinCont();
  G__cpp_setup_tagtabledict_CLPBinCont();

  G__cpp_setup_inheritancedict_CLPBinCont();

  G__cpp_setup_typetabledict_CLPBinCont();

  G__cpp_setup_memvardict_CLPBinCont();

  G__cpp_setup_memfuncdict_CLPBinCont();
  G__cpp_setup_globaldict_CLPBinCont();
  G__cpp_setup_funcdict_CLPBinCont();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncdict_CLPBinCont();
  return;
}
class G__cpp_setup_initdict_CLPBinCont {
  public:
    G__cpp_setup_initdict_CLPBinCont() { G__add_setup_func("dict_CLPBinCont",(G__incsetup)(&G__cpp_setupdict_CLPBinCont)); G__call_setup_funcs(); }
   ~G__cpp_setup_initdict_CLPBinCont() { G__remove_setup_func("dict_CLPBinCont"); }
};
G__cpp_setup_initdict_CLPBinCont G__cpp_setup_initializerdict_CLPBinCont;

