//
// File generated by /cdf/code/cdfsoft/products/root/v5_22_00j-GCC_3_4_6/Linux+2.6/bin/rootcint at Sun Nov  7 18:30:21 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "dict_CLPFunctionoid2.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void CLPFunctionoid2_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void CLPFunctionoid2_Dictionary();
   static void *new_CLPFunctionoid2(void *p = 0);
   static void *newArray_CLPFunctionoid2(Long_t size, void *p);
   static void delete_CLPFunctionoid2(void *p);
   static void deleteArray_CLPFunctionoid2(void *p);
   static void destruct_CLPFunctionoid2(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::CLPFunctionoid2*)
   {
      ::CLPFunctionoid2 *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::CLPFunctionoid2),0);
      static ::ROOT::TGenericClassInfo 
         instance("CLPFunctionoid2", "interface/CLPFunctionoid2.h", 9,
                  typeid(::CLPFunctionoid2), DefineBehavior(ptr, ptr),
                  0, &CLPFunctionoid2_Dictionary, isa_proxy, 0,
                  sizeof(::CLPFunctionoid2) );
      instance.SetNew(&new_CLPFunctionoid2);
      instance.SetNewArray(&newArray_CLPFunctionoid2);
      instance.SetDelete(&delete_CLPFunctionoid2);
      instance.SetDeleteArray(&deleteArray_CLPFunctionoid2);
      instance.SetDestructor(&destruct_CLPFunctionoid2);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::CLPFunctionoid2*)
   {
      return GenerateInitInstanceLocal((::CLPFunctionoid2*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::CLPFunctionoid2*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void CLPFunctionoid2_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::CLPFunctionoid2*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_CLPFunctionoid2(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::CLPFunctionoid2 : new ::CLPFunctionoid2;
   }
   static void *newArray_CLPFunctionoid2(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::CLPFunctionoid2[nElements] : new ::CLPFunctionoid2[nElements];
   }
   // Wrapper around operator delete
   static void delete_CLPFunctionoid2(void *p) {
      delete ((::CLPFunctionoid2*)p);
   }
   static void deleteArray_CLPFunctionoid2(void *p) {
      delete [] ((::CLPFunctionoid2*)p);
   }
   static void destruct_CLPFunctionoid2(void *p) {
      typedef ::CLPFunctionoid2 current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::CLPFunctionoid2

/********************************************************
* objects/dict_CLPFunctionoid2.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && (__GNUC__ > 3) && (__GNUC_MINOR__ > 1)
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtabledict_CLPFunctionoid2();

extern "C" void G__set_cpp_environmentdict_CLPFunctionoid2() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("CLPFunctionoid2.h");
  G__cpp_reset_tagtabledict_CLPFunctionoid2();
}
#include <new>
extern "C" int G__cpp_dllrevdict_CLPFunctionoid2() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* CLPFunctionoid2 */
static int G__dict_CLPFunctionoid2_199_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CLPFunctionoid2* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CLPFunctionoid2[n];
     } else {
       p = new((void*) gvp) CLPFunctionoid2[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CLPFunctionoid2;
     } else {
       p = new((void*) gvp) CLPFunctionoid2;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_CLPFunctionoid2));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPFunctionoid2_199_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const CLPFunctionoid2*) G__getstructoffset())->operator()((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__dict_CLPFunctionoid2_199_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   CLPFunctionoid2* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new CLPFunctionoid2(*(CLPFunctionoid2*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_CLPFunctionoid2));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef CLPFunctionoid2 G__TCLPFunctionoid2;
static int G__dict_CLPFunctionoid2_199_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (CLPFunctionoid2*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((CLPFunctionoid2*) (soff+(sizeof(CLPFunctionoid2)*i)))->~G__TCLPFunctionoid2();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (CLPFunctionoid2*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((CLPFunctionoid2*) (soff))->~G__TCLPFunctionoid2();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__dict_CLPFunctionoid2_199_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CLPFunctionoid2* dest = (CLPFunctionoid2*) G__getstructoffset();
   *dest = *(CLPFunctionoid2*) libp->para[0].ref;
   const CLPFunctionoid2& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* CLPFunctionoid2 */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncdict_CLPFunctionoid2 {
 public:
  G__Sizep2memfuncdict_CLPFunctionoid2(): p(&G__Sizep2memfuncdict_CLPFunctionoid2::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncdict_CLPFunctionoid2::*p)();
};

size_t G__get_sizep2memfuncdict_CLPFunctionoid2()
{
  G__Sizep2memfuncdict_CLPFunctionoid2 a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancedict_CLPFunctionoid2() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetabledict_CLPFunctionoid2() {

   /* Setting up typedef entry */
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* CLPFunctionoid2 */
static void G__setup_memvarCLPFunctionoid2(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_CLPFunctionoid2));
   { CLPFunctionoid2 *p; p=(CLPFunctionoid2*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvardict_CLPFunctionoid2() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncCLPFunctionoid2(void) {
   /* CLPFunctionoid2 */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_CLPFunctionoid2));
   G__memfunc_setup("CLPFunctionoid2",1427,G__dict_CLPFunctionoid2_199_0_1, 105, G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_CLPFunctionoid2), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator()",957,G__dict_CLPFunctionoid2_199_0_2, 100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - alpha d - - 0 - beta", (char*)NULL, (void*) NULL, 1);
   // automatic copy constructor
   G__memfunc_setup("CLPFunctionoid2", 1427, G__dict_CLPFunctionoid2_199_0_3, (int) ('i'), G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_CLPFunctionoid2), -1, 0, 1, 1, 1, 0, "u 'CLPFunctionoid2' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~CLPFunctionoid2", 1553, G__dict_CLPFunctionoid2_199_0_4, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__dict_CLPFunctionoid2_199_0_5, (int) ('u'), G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_CLPFunctionoid2), -1, 1, 1, 1, 1, 0, "u 'CLPFunctionoid2' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncdict_CLPFunctionoid2() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaldict_CLPFunctionoid2() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcdict_CLPFunctionoid2() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__dict_CLPFunctionoid2LN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPFunctionoid2LN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPFunctionoid2LN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_CLPFunctionoid2LN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPFunctionoid2LN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_CLPFunctionoid2LN_CLPFunctionoid2 = { "CLPFunctionoid2" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtabledict_CLPFunctionoid2() {
  G__dict_CLPFunctionoid2LN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__dict_CLPFunctionoid2LN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__dict_CLPFunctionoid2LN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_CLPFunctionoid2LN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__dict_CLPFunctionoid2LN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_CLPFunctionoid2LN_CLPFunctionoid2.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtabledict_CLPFunctionoid2() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__dict_CLPFunctionoid2LN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPFunctionoid2LN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPFunctionoid2LN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPFunctionoid2LN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPFunctionoid2LN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__dict_CLPFunctionoid2LN_CLPFunctionoid2),sizeof(CLPFunctionoid2),-1,1280,(char*)NULL,G__setup_memvarCLPFunctionoid2,G__setup_memfuncCLPFunctionoid2);
}
extern "C" void G__cpp_setupdict_CLPFunctionoid2(void) {
  G__check_setup_version(30051515,"G__cpp_setupdict_CLPFunctionoid2()");
  G__set_cpp_environmentdict_CLPFunctionoid2();
  G__cpp_setup_tagtabledict_CLPFunctionoid2();

  G__cpp_setup_inheritancedict_CLPFunctionoid2();

  G__cpp_setup_typetabledict_CLPFunctionoid2();

  G__cpp_setup_memvardict_CLPFunctionoid2();

  G__cpp_setup_memfuncdict_CLPFunctionoid2();
  G__cpp_setup_globaldict_CLPFunctionoid2();
  G__cpp_setup_funcdict_CLPFunctionoid2();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncdict_CLPFunctionoid2();
  return;
}
class G__cpp_setup_initdict_CLPFunctionoid2 {
  public:
    G__cpp_setup_initdict_CLPFunctionoid2() { G__add_setup_func("dict_CLPFunctionoid2",(G__incsetup)(&G__cpp_setupdict_CLPFunctionoid2)); G__call_setup_funcs(); }
   ~G__cpp_setup_initdict_CLPFunctionoid2() { G__remove_setup_func("dict_CLPFunctionoid2"); }
};
G__cpp_setup_initdict_CLPFunctionoid2 G__cpp_setup_initializerdict_CLPFunctionoid2;

