/********************************************************************
* objects/dict_CLPBinCont.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error objects/dict_CLPBinCont.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtabledict_CLPBinCont();
extern void G__cpp_setup_inheritancedict_CLPBinCont();
extern void G__cpp_setup_typetabledict_CLPBinCont();
extern void G__cpp_setup_memvardict_CLPBinCont();
extern void G__cpp_setup_globaldict_CLPBinCont();
extern void G__cpp_setup_memfuncdict_CLPBinCont();
extern void G__cpp_setup_funcdict_CLPBinCont();
extern void G__set_cpp_environmentdict_CLPBinCont();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "CLPBinCont.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dict_CLPBinContLN_TClass;
extern G__linked_taginfo G__dict_CLPBinContLN_TBuffer;
extern G__linked_taginfo G__dict_CLPBinContLN_TMemberInspector;
extern G__linked_taginfo G__dict_CLPBinContLN_TObject;
extern G__linked_taginfo G__dict_CLPBinContLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__dict_CLPBinContLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dict_CLPBinContLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_CLPBinContLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__dict_CLPBinContLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_CLPBinContLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__dict_CLPBinContLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__dict_CLPBinContLN_TH1F;
extern G__linked_taginfo G__dict_CLPBinContLN_TGraph;
extern G__linked_taginfo G__dict_CLPBinContLN_vectorlECLPBincOallocatorlECLPBingRsPgR;
extern G__linked_taginfo G__dict_CLPBinContLN_vectorlECLPBincOallocatorlECLPBingRsPgRcLcLiterator;
extern G__linked_taginfo G__dict_CLPBinContLN_reverse_iteratorlEvectorlECLPBincOallocatorlECLPBingRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_CLPBinContLN_CLPFunctionoid2;
extern G__linked_taginfo G__dict_CLPBinContLN_CLPBinCont;
extern G__linked_taginfo G__dict_CLPBinContLN_maplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgR;
extern G__linked_taginfo G__dict_CLPBinContLN_maplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__dict_CLPBinContLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__dict_CLPBinContLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__dict_CLPBinContLN_reverse_iteratorlEvectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
