//
// File generated by /cdf/code/cdfsoft/products/root/v5_22_00j-GCC_3_4_6/Linux+2.6/bin/rootcint at Sun Nov  7 18:30:21 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "dict_CLPFunctionoid2Slide.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void CLPFunctionoid2Slide_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void CLPFunctionoid2Slide_Dictionary();
   static void delete_CLPFunctionoid2Slide(void *p);
   static void deleteArray_CLPFunctionoid2Slide(void *p);
   static void destruct_CLPFunctionoid2Slide(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::CLPFunctionoid2Slide*)
   {
      ::CLPFunctionoid2Slide *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::CLPFunctionoid2Slide),0);
      static ::ROOT::TGenericClassInfo 
         instance("CLPFunctionoid2Slide", "interface/CLPFunctionoid2Slide.h", 11,
                  typeid(::CLPFunctionoid2Slide), DefineBehavior(ptr, ptr),
                  0, &CLPFunctionoid2Slide_Dictionary, isa_proxy, 0,
                  sizeof(::CLPFunctionoid2Slide) );
      instance.SetDelete(&delete_CLPFunctionoid2Slide);
      instance.SetDeleteArray(&deleteArray_CLPFunctionoid2Slide);
      instance.SetDestructor(&destruct_CLPFunctionoid2Slide);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::CLPFunctionoid2Slide*)
   {
      return GenerateInitInstanceLocal((::CLPFunctionoid2Slide*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::CLPFunctionoid2Slide*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void CLPFunctionoid2Slide_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::CLPFunctionoid2Slide*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrapper around operator delete
   static void delete_CLPFunctionoid2Slide(void *p) {
      delete ((::CLPFunctionoid2Slide*)p);
   }
   static void deleteArray_CLPFunctionoid2Slide(void *p) {
      delete [] ((::CLPFunctionoid2Slide*)p);
   }
   static void destruct_CLPFunctionoid2Slide(void *p) {
      typedef ::CLPFunctionoid2Slide current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::CLPFunctionoid2Slide

/********************************************************
* objects/dict_CLPFunctionoid2Slide.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && (__GNUC__ > 3) && (__GNUC_MINOR__ > 1)
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtabledict_CLPFunctionoid2Slide();

extern "C" void G__set_cpp_environmentdict_CLPFunctionoid2Slide() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("CLPFunctionoid2Slide.h");
  G__cpp_reset_tagtabledict_CLPFunctionoid2Slide();
}
#include <new>
extern "C" int G__cpp_dllrevdict_CLPFunctionoid2Slide() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* CLPFunctionoid2Slide */
static int G__dict_CLPFunctionoid2Slide_200_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CLPFunctionoid2Slide* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new CLPFunctionoid2Slide((double) G__double(libp->para[0]));
   } else {
     p = new((void*) gvp) CLPFunctionoid2Slide((double) G__double(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_CLPFunctionoid2Slide));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__dict_CLPFunctionoid2Slide_200_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   CLPFunctionoid2Slide* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new CLPFunctionoid2Slide(*(CLPFunctionoid2Slide*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_CLPFunctionoid2Slide));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef CLPFunctionoid2Slide G__TCLPFunctionoid2Slide;
static int G__dict_CLPFunctionoid2Slide_200_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (CLPFunctionoid2Slide*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((CLPFunctionoid2Slide*) (soff+(sizeof(CLPFunctionoid2Slide)*i)))->~G__TCLPFunctionoid2Slide();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (CLPFunctionoid2Slide*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((CLPFunctionoid2Slide*) (soff))->~G__TCLPFunctionoid2Slide();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__dict_CLPFunctionoid2Slide_200_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CLPFunctionoid2Slide* dest = (CLPFunctionoid2Slide*) G__getstructoffset();
   *dest = *(CLPFunctionoid2Slide*) libp->para[0].ref;
   const CLPFunctionoid2Slide& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* CLPFunctionoid2Slide */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncdict_CLPFunctionoid2Slide {
 public:
  G__Sizep2memfuncdict_CLPFunctionoid2Slide(): p(&G__Sizep2memfuncdict_CLPFunctionoid2Slide::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncdict_CLPFunctionoid2Slide::*p)();
};

size_t G__get_sizep2memfuncdict_CLPFunctionoid2Slide()
{
  G__Sizep2memfuncdict_CLPFunctionoid2Slide a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancedict_CLPFunctionoid2Slide() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_CLPFunctionoid2Slide))) {
     CLPFunctionoid2Slide *G__Lderived;
     G__Lderived=(CLPFunctionoid2Slide*)0x1000;
     {
       CLPFunctionoid2 *G__Lpbase=(CLPFunctionoid2*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_CLPFunctionoid2Slide),G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_CLPFunctionoid2),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetabledict_CLPFunctionoid2Slide() {

   /* Setting up typedef entry */
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* CLPFunctionoid2Slide */
static void G__setup_memvarCLPFunctionoid2Slide(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_CLPFunctionoid2Slide));
   { CLPFunctionoid2Slide *p; p=(CLPFunctionoid2Slide*)0x1000; if (p) { }
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"m_percentage=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvardict_CLPFunctionoid2Slide() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncCLPFunctionoid2Slide(void) {
   /* CLPFunctionoid2Slide */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_CLPFunctionoid2Slide));
   G__memfunc_setup("CLPFunctionoid2Slide",1924,G__dict_CLPFunctionoid2Slide_200_0_1, 105, G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_CLPFunctionoid2Slide), -1, 0, 1, 1, 1, 0, "d - - 0 - percentage", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator()",957,(G__InterfaceMethod) NULL,100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - alpha d - - 0 - beta", (char*)NULL, (void*) NULL, 1);
   // automatic copy constructor
   G__memfunc_setup("CLPFunctionoid2Slide", 1924, G__dict_CLPFunctionoid2Slide_200_0_3, (int) ('i'), G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_CLPFunctionoid2Slide), -1, 0, 1, 1, 1, 0, "u 'CLPFunctionoid2Slide' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~CLPFunctionoid2Slide", 2050, G__dict_CLPFunctionoid2Slide_200_0_4, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__dict_CLPFunctionoid2Slide_200_0_5, (int) ('u'), G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_CLPFunctionoid2Slide), -1, 1, 1, 1, 1, 0, "u 'CLPFunctionoid2Slide' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncdict_CLPFunctionoid2Slide() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaldict_CLPFunctionoid2Slide() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcdict_CLPFunctionoid2Slide() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__dict_CLPFunctionoid2SlideLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPFunctionoid2SlideLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPFunctionoid2SlideLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_CLPFunctionoid2SlideLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPFunctionoid2SlideLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_CLPFunctionoid2SlideLN_CLPFunctionoid2 = { "CLPFunctionoid2" , 99 , -1 };
G__linked_taginfo G__dict_CLPFunctionoid2SlideLN_CLPFunctionoid2Slide = { "CLPFunctionoid2Slide" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtabledict_CLPFunctionoid2Slide() {
  G__dict_CLPFunctionoid2SlideLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__dict_CLPFunctionoid2SlideLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__dict_CLPFunctionoid2SlideLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_CLPFunctionoid2SlideLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__dict_CLPFunctionoid2SlideLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_CLPFunctionoid2SlideLN_CLPFunctionoid2.tagnum = -1 ;
  G__dict_CLPFunctionoid2SlideLN_CLPFunctionoid2Slide.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtabledict_CLPFunctionoid2Slide() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__dict_CLPFunctionoid2SlideLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPFunctionoid2SlideLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPFunctionoid2SlideLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPFunctionoid2SlideLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPFunctionoid2SlideLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPFunctionoid2SlideLN_CLPFunctionoid2);
   G__tagtable_setup(G__get_linked_tagnum(&G__dict_CLPFunctionoid2SlideLN_CLPFunctionoid2Slide),sizeof(CLPFunctionoid2Slide),-1,32768,(char*)NULL,G__setup_memvarCLPFunctionoid2Slide,G__setup_memfuncCLPFunctionoid2Slide);
}
extern "C" void G__cpp_setupdict_CLPFunctionoid2Slide(void) {
  G__check_setup_version(30051515,"G__cpp_setupdict_CLPFunctionoid2Slide()");
  G__set_cpp_environmentdict_CLPFunctionoid2Slide();
  G__cpp_setup_tagtabledict_CLPFunctionoid2Slide();

  G__cpp_setup_inheritancedict_CLPFunctionoid2Slide();

  G__cpp_setup_typetabledict_CLPFunctionoid2Slide();

  G__cpp_setup_memvardict_CLPFunctionoid2Slide();

  G__cpp_setup_memfuncdict_CLPFunctionoid2Slide();
  G__cpp_setup_globaldict_CLPFunctionoid2Slide();
  G__cpp_setup_funcdict_CLPFunctionoid2Slide();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncdict_CLPFunctionoid2Slide();
  return;
}
class G__cpp_setup_initdict_CLPFunctionoid2Slide {
  public:
    G__cpp_setup_initdict_CLPFunctionoid2Slide() { G__add_setup_func("dict_CLPFunctionoid2Slide",(G__incsetup)(&G__cpp_setupdict_CLPFunctionoid2Slide)); G__call_setup_funcs(); }
   ~G__cpp_setup_initdict_CLPFunctionoid2Slide() { G__remove_setup_func("dict_CLPFunctionoid2Slide"); }
};
G__cpp_setup_initdict_CLPFunctionoid2Slide G__cpp_setup_initializerdict_CLPFunctionoid2Slide;

