/********************************************************************
* objects/dict_CLPBin.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error objects/dict_CLPBin.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtabledict_CLPBin();
extern void G__cpp_setup_inheritancedict_CLPBin();
extern void G__cpp_setup_typetabledict_CLPBin();
extern void G__cpp_setup_memvardict_CLPBin();
extern void G__cpp_setup_globaldict_CLPBin();
extern void G__cpp_setup_memfuncdict_CLPBin();
extern void G__cpp_setup_funcdict_CLPBin();
extern void G__set_cpp_environmentdict_CLPBin();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "CLPBin.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dict_CLPBinLN_TClass;
extern G__linked_taginfo G__dict_CLPBinLN_TBuffer;
extern G__linked_taginfo G__dict_CLPBinLN_TMemberInspector;
extern G__linked_taginfo G__dict_CLPBinLN_TObject;
extern G__linked_taginfo G__dict_CLPBinLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__dict_CLPBinLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dict_CLPBinLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_CLPBinLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__dict_CLPBinLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_CLPBinLN_CLPBin;
extern G__linked_taginfo G__dict_CLPBinLN_vectorlECLPBincOallocatorlECLPBingRsPgR;
extern G__linked_taginfo G__dict_CLPBinLN_vectorlECLPBincOallocatorlECLPBingRsPgRcLcLiterator;
extern G__linked_taginfo G__dict_CLPBinLN_reverse_iteratorlEvectorlECLPBincOallocatorlECLPBingRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
