//
// File generated by /cdf/code/cdfsoft/products/root/v5_22_00j-GCC_3_4_6/Linux+2.6/bin/rootcint at Sun Nov  7 18:30:21 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "dict_CLPTemplateMorph.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void CLPTemplateMorph_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_CLPTemplateMorph(void *p = 0);
   static void *newArray_CLPTemplateMorph(Long_t size, void *p);
   static void delete_CLPTemplateMorph(void *p);
   static void deleteArray_CLPTemplateMorph(void *p);
   static void destruct_CLPTemplateMorph(void *p);
   static void directoryAutoAdd_CLPTemplateMorph(void *p, TDirectory *dir);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::CLPTemplateMorph*)
   {
      ::CLPTemplateMorph *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::CLPTemplateMorph >(0);
      static ::ROOT::TGenericClassInfo 
         instance("CLPTemplateMorph", ::CLPTemplateMorph::Class_Version(), "interface/CLPTemplateMorph.h", 15,
                  typeid(::CLPTemplateMorph), DefineBehavior(ptr, ptr),
                  &::CLPTemplateMorph::Dictionary, isa_proxy, 0,
                  sizeof(::CLPTemplateMorph) );
      instance.SetNew(&new_CLPTemplateMorph);
      instance.SetNewArray(&newArray_CLPTemplateMorph);
      instance.SetDelete(&delete_CLPTemplateMorph);
      instance.SetDeleteArray(&deleteArray_CLPTemplateMorph);
      instance.SetDestructor(&destruct_CLPTemplateMorph);
      instance.SetDirectoryAutoAdd(&directoryAutoAdd_CLPTemplateMorph);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::CLPTemplateMorph*)
   {
      return GenerateInitInstanceLocal((::CLPTemplateMorph*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::CLPTemplateMorph*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *CLPTemplateMorph::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *CLPTemplateMorph::Class_Name()
{
   return "CLPTemplateMorph";
}

//______________________________________________________________________________
const char *CLPTemplateMorph::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CLPTemplateMorph*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int CLPTemplateMorph::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CLPTemplateMorph*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void CLPTemplateMorph::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CLPTemplateMorph*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *CLPTemplateMorph::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CLPTemplateMorph*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void CLPTemplateMorph::Streamer(TBuffer &R__b)
{
   // Stream an object of class CLPTemplateMorph.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TH1F::Streamer(R__b);
      R__b >> m_dontRemovePoints;
      R__b >> m_smoothDeltas;
      R__b >> m_outputAll;
      R__b >> m_isMorphContainer;
      R__b >> m_noUnderOverflow;
      {
         CLPTemplateMorph::DVec &R__stl =  m_paramVec;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         CLPTemplateMorph::DVec &R__stl =  m_centerVec;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         CLPTemplateMorph::SVec &R__stl =  m_nameVec;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            string R__t;
            {TString R__str;
             R__str.Streamer(R__b);
             R__t = R__str.Data();}
            R__stl.push_back(R__t);
         }
      }
      {
         CLPTemplateMorph::IVec &R__stl =  m_indexVec;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            int R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         CLPTemplateMorph::PtrVec &R__stl =  m_ptrVec;
         R__stl.clear();
         TClass *R__tcl1 = TBuffer::GetClass(typeid(CLPTemplateMorph));
         if (R__tcl1==0) {
            Error("m_ptrVec streamer","Missing the TClass object for CLPTemplateMorph!");
            return;
         }
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            CLPTemplateMorph* R__t;
            R__t = (CLPTemplateMorph*)R__b.ReadObjectAny(R__tcl1);
            R__stl.push_back(R__t);
         }
      }
      m_defaultBC.Streamer(R__b);
      {
         CLPBinCont::DMapVec &R__stl =  m_deltaMorphMapVec;
         R__stl.clear();
         TClass *R__tcl1 = TBuffer::GetClass(typeid(map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > >));
         if (R__tcl1==0) {
            Error("m_deltaMorphMapVec streamer","Missing the TClass object for map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > >!");
            return;
         }
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > > R__t;
            R__b.StreamObject(&R__t,R__tcl1);
            R__stl.push_back(R__t);
         }
      }
      R__b.CheckByteCount(R__s, R__c, CLPTemplateMorph::IsA());
   } else {
      R__c = R__b.WriteVersion(CLPTemplateMorph::IsA(), kTRUE);
      TH1F::Streamer(R__b);
      R__b << m_dontRemovePoints;
      R__b << m_smoothDeltas;
      R__b << m_outputAll;
      R__b << m_isMorphContainer;
      R__b << m_noUnderOverflow;
      {
         CLPTemplateMorph::DVec &R__stl =  m_paramVec;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            CLPTemplateMorph::DVec::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         CLPTemplateMorph::DVec &R__stl =  m_centerVec;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            CLPTemplateMorph::DVec::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         CLPTemplateMorph::SVec &R__stl =  m_nameVec;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            CLPTemplateMorph::SVec::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            {TString R__str((*R__k).c_str());
             R__str.Streamer(R__b);};
            }
         }
      }
      {
         CLPTemplateMorph::IVec &R__stl =  m_indexVec;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            CLPTemplateMorph::IVec::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         CLPTemplateMorph::PtrVec &R__stl =  m_ptrVec;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            CLPTemplateMorph::PtrVec::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      m_defaultBC.Streamer(R__b);
      {
         CLPBinCont::DMapVec &R__stl =  m_deltaMorphMapVec;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
         TClass *R__tcl1 = TBuffer::GetClass(typeid(map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > >));
         if (R__tcl1==0) {
            Error("m_deltaMorphMapVec streamer","Missing the TClass object for map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > >!");
            return;
         }
            CLPBinCont::DMapVec::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b.StreamObject((map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > >*)&(*R__k),R__tcl1);
            }
         }
      }
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void CLPTemplateMorph::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class CLPTemplateMorph.
      TClass *R__cl = ::CLPTemplateMorph::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "m_dontRemovePoints", &m_dontRemovePoints);
      R__insp.Inspect(R__cl, R__parent, "m_smoothDeltas", &m_smoothDeltas);
      R__insp.Inspect(R__cl, R__parent, "m_outputAll", &m_outputAll);
      R__insp.Inspect(R__cl, R__parent, "m_isMorphContainer", &m_isMorphContainer);
      R__insp.Inspect(R__cl, R__parent, "m_noUnderOverflow", &m_noUnderOverflow);
      R__insp.Inspect(R__cl, R__parent, "m_paramVec", (void*)&m_paramVec);
      ::ROOT::GenericShowMembers("CLPTemplateMorph::DVec", (void*)&m_paramVec, R__insp, strcat(R__parent,"m_paramVec."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "m_centerVec", (void*)&m_centerVec);
      ::ROOT::GenericShowMembers("CLPTemplateMorph::DVec", (void*)&m_centerVec, R__insp, strcat(R__parent,"m_centerVec."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "m_nameVec", (void*)&m_nameVec);
      ::ROOT::GenericShowMembers("CLPTemplateMorph::SVec", (void*)&m_nameVec, R__insp, strcat(R__parent,"m_nameVec."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "m_indexVec", (void*)&m_indexVec);
      ::ROOT::GenericShowMembers("CLPTemplateMorph::IVec", (void*)&m_indexVec, R__insp, strcat(R__parent,"m_indexVec."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "m_ptrVec", (void*)&m_ptrVec);
      ::ROOT::GenericShowMembers("CLPTemplateMorph::PtrVec", (void*)&m_ptrVec, R__insp, strcat(R__parent,"m_ptrVec."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "m_defaultBC", &m_defaultBC);
      m_defaultBC.ShowMembers(R__insp, strcat(R__parent,"m_defaultBC.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "m_deltaMorphMapVec", (void*)&m_deltaMorphMapVec);
      ::ROOT::GenericShowMembers("CLPBinCont::DMapVec", (void*)&m_deltaMorphMapVec, R__insp, strcat(R__parent,"m_deltaMorphMapVec."),false);
      R__parent[R__ncp] = 0;
      TH1F::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_CLPTemplateMorph(void *p) {
      return  p ? new(p) ::CLPTemplateMorph : new ::CLPTemplateMorph;
   }
   static void *newArray_CLPTemplateMorph(Long_t nElements, void *p) {
      return p ? new(p) ::CLPTemplateMorph[nElements] : new ::CLPTemplateMorph[nElements];
   }
   // Wrapper around operator delete
   static void delete_CLPTemplateMorph(void *p) {
      delete ((::CLPTemplateMorph*)p);
   }
   static void deleteArray_CLPTemplateMorph(void *p) {
      delete [] ((::CLPTemplateMorph*)p);
   }
   static void destruct_CLPTemplateMorph(void *p) {
      typedef ::CLPTemplateMorph current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around the directory auto add.
   static void directoryAutoAdd_CLPTemplateMorph(void *p, TDirectory *dir) {
      ((::CLPTemplateMorph*)p)->DirectoryAutoAdd(dir);
   }
} // end of namespace ROOT for class ::CLPTemplateMorph

namespace ROOT {
   void maplEdoublecOCLPBinContgR_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void maplEdoublecOCLPBinContgR_Dictionary();
   static void *new_maplEdoublecOCLPBinContgR(void *p = 0);
   static void *newArray_maplEdoublecOCLPBinContgR(Long_t size, void *p);
   static void delete_maplEdoublecOCLPBinContgR(void *p);
   static void deleteArray_maplEdoublecOCLPBinContgR(void *p);
   static void destruct_maplEdoublecOCLPBinContgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const map<double,CLPBinCont>*)
   {
      map<double,CLPBinCont> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<double,CLPBinCont>),0);
      static ::ROOT::TGenericClassInfo 
         instance("map<double,CLPBinCont>", -2, "prec_stl/map", 63,
                  typeid(map<double,CLPBinCont>), DefineBehavior(ptr, ptr),
                  0, &maplEdoublecOCLPBinContgR_Dictionary, isa_proxy, 0,
                  sizeof(map<double,CLPBinCont>) );
      instance.SetNew(&new_maplEdoublecOCLPBinContgR);
      instance.SetNewArray(&newArray_maplEdoublecOCLPBinContgR);
      instance.SetDelete(&delete_maplEdoublecOCLPBinContgR);
      instance.SetDeleteArray(&deleteArray_maplEdoublecOCLPBinContgR);
      instance.SetDestructor(&destruct_maplEdoublecOCLPBinContgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<double,CLPBinCont> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const map<double,CLPBinCont>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void maplEdoublecOCLPBinContgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const map<double,CLPBinCont>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_maplEdoublecOCLPBinContgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<double,CLPBinCont> : new map<double,CLPBinCont>;
   }
   static void *newArray_maplEdoublecOCLPBinContgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<double,CLPBinCont>[nElements] : new map<double,CLPBinCont>[nElements];
   }
   // Wrapper around operator delete
   static void delete_maplEdoublecOCLPBinContgR(void *p) {
      delete ((map<double,CLPBinCont>*)p);
   }
   static void deleteArray_maplEdoublecOCLPBinContgR(void *p) {
      delete [] ((map<double,CLPBinCont>*)p);
   }
   static void destruct_maplEdoublecOCLPBinContgR(void *p) {
      typedef map<double,CLPBinCont> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class map<double,CLPBinCont>

namespace ROOT {
   void vectorlECLPTemplateMorphmUgR_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void vectorlECLPTemplateMorphmUgR_Dictionary();
   static void *new_vectorlECLPTemplateMorphmUgR(void *p = 0);
   static void *newArray_vectorlECLPTemplateMorphmUgR(Long_t size, void *p);
   static void delete_vectorlECLPTemplateMorphmUgR(void *p);
   static void deleteArray_vectorlECLPTemplateMorphmUgR(void *p);
   static void destruct_vectorlECLPTemplateMorphmUgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<CLPTemplateMorph*>*)
   {
      vector<CLPTemplateMorph*> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<CLPTemplateMorph*>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<CLPTemplateMorph*>", -2, "prec_stl/vector", 49,
                  typeid(vector<CLPTemplateMorph*>), DefineBehavior(ptr, ptr),
                  0, &vectorlECLPTemplateMorphmUgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<CLPTemplateMorph*>) );
      instance.SetNew(&new_vectorlECLPTemplateMorphmUgR);
      instance.SetNewArray(&newArray_vectorlECLPTemplateMorphmUgR);
      instance.SetDelete(&delete_vectorlECLPTemplateMorphmUgR);
      instance.SetDeleteArray(&deleteArray_vectorlECLPTemplateMorphmUgR);
      instance.SetDestructor(&destruct_vectorlECLPTemplateMorphmUgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<CLPTemplateMorph*> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<CLPTemplateMorph*>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlECLPTemplateMorphmUgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<CLPTemplateMorph*>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlECLPTemplateMorphmUgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<CLPTemplateMorph*> : new vector<CLPTemplateMorph*>;
   }
   static void *newArray_vectorlECLPTemplateMorphmUgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<CLPTemplateMorph*>[nElements] : new vector<CLPTemplateMorph*>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlECLPTemplateMorphmUgR(void *p) {
      delete ((vector<CLPTemplateMorph*>*)p);
   }
   static void deleteArray_vectorlECLPTemplateMorphmUgR(void *p) {
      delete [] ((vector<CLPTemplateMorph*>*)p);
   }
   static void destruct_vectorlECLPTemplateMorphmUgR(void *p) {
      typedef vector<CLPTemplateMorph*> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<CLPTemplateMorph*>

namespace ROOT {
   void vectorlEdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void vectorlEdoublegR_Dictionary();
   static void *new_vectorlEdoublegR(void *p = 0);
   static void *newArray_vectorlEdoublegR(Long_t size, void *p);
   static void delete_vectorlEdoublegR(void *p);
   static void deleteArray_vectorlEdoublegR(void *p);
   static void destruct_vectorlEdoublegR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<double>*)
   {
      vector<double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<double>", -2, "vector.dll", 0,
                  typeid(vector<double>), DefineBehavior(ptr, ptr),
                  0, &vectorlEdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(vector<double>) );
      instance.SetNew(&new_vectorlEdoublegR);
      instance.SetNewArray(&newArray_vectorlEdoublegR);
      instance.SetDelete(&delete_vectorlEdoublegR);
      instance.SetDeleteArray(&deleteArray_vectorlEdoublegR);
      instance.SetDestructor(&destruct_vectorlEdoublegR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEdoublegR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<double>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double> : new vector<double>;
   }
   static void *newArray_vectorlEdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double>[nElements] : new vector<double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEdoublegR(void *p) {
      delete ((vector<double>*)p);
   }
   static void deleteArray_vectorlEdoublegR(void *p) {
      delete [] ((vector<double>*)p);
   }
   static void destruct_vectorlEdoublegR(void *p) {
      typedef vector<double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<double>

namespace ROOT {
   void vectorlEintgR_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void vectorlEintgR_Dictionary();
   static void *new_vectorlEintgR(void *p = 0);
   static void *newArray_vectorlEintgR(Long_t size, void *p);
   static void delete_vectorlEintgR(void *p);
   static void deleteArray_vectorlEintgR(void *p);
   static void destruct_vectorlEintgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<int>*)
   {
      vector<int> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<int>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<int>", -2, "prec_stl/vector", 49,
                  typeid(vector<int>), DefineBehavior(ptr, ptr),
                  0, &vectorlEintgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<int>) );
      instance.SetNew(&new_vectorlEintgR);
      instance.SetNewArray(&newArray_vectorlEintgR);
      instance.SetDelete(&delete_vectorlEintgR);
      instance.SetDeleteArray(&deleteArray_vectorlEintgR);
      instance.SetDestructor(&destruct_vectorlEintgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<int> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<int>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEintgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<int>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEintgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int> : new vector<int>;
   }
   static void *newArray_vectorlEintgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int>[nElements] : new vector<int>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEintgR(void *p) {
      delete ((vector<int>*)p);
   }
   static void deleteArray_vectorlEintgR(void *p) {
      delete [] ((vector<int>*)p);
   }
   static void destruct_vectorlEintgR(void *p) {
      typedef vector<int> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<int>

namespace ROOT {
   void vectorlEmaplEdoublecOCLPBinContgRsPgR_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void vectorlEmaplEdoublecOCLPBinContgRsPgR_Dictionary();
   static void *new_vectorlEmaplEdoublecOCLPBinContgRsPgR(void *p = 0);
   static void *newArray_vectorlEmaplEdoublecOCLPBinContgRsPgR(Long_t size, void *p);
   static void delete_vectorlEmaplEdoublecOCLPBinContgRsPgR(void *p);
   static void deleteArray_vectorlEmaplEdoublecOCLPBinContgRsPgR(void *p);
   static void destruct_vectorlEmaplEdoublecOCLPBinContgRsPgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<map<double,CLPBinCont> >*)
   {
      vector<map<double,CLPBinCont> > *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<map<double,CLPBinCont> >),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<map<double,CLPBinCont> >", -2, "prec_stl/vector", 49,
                  typeid(vector<map<double,CLPBinCont> >), DefineBehavior(ptr, ptr),
                  0, &vectorlEmaplEdoublecOCLPBinContgRsPgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<map<double,CLPBinCont> >) );
      instance.SetNew(&new_vectorlEmaplEdoublecOCLPBinContgRsPgR);
      instance.SetNewArray(&newArray_vectorlEmaplEdoublecOCLPBinContgRsPgR);
      instance.SetDelete(&delete_vectorlEmaplEdoublecOCLPBinContgRsPgR);
      instance.SetDeleteArray(&deleteArray_vectorlEmaplEdoublecOCLPBinContgRsPgR);
      instance.SetDestructor(&destruct_vectorlEmaplEdoublecOCLPBinContgRsPgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<map<double,CLPBinCont> > >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<map<double,CLPBinCont> >*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEmaplEdoublecOCLPBinContgRsPgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<map<double,CLPBinCont> >*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEmaplEdoublecOCLPBinContgRsPgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<map<double,CLPBinCont> > : new vector<map<double,CLPBinCont> >;
   }
   static void *newArray_vectorlEmaplEdoublecOCLPBinContgRsPgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<map<double,CLPBinCont> >[nElements] : new vector<map<double,CLPBinCont> >[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEmaplEdoublecOCLPBinContgRsPgR(void *p) {
      delete ((vector<map<double,CLPBinCont> >*)p);
   }
   static void deleteArray_vectorlEmaplEdoublecOCLPBinContgRsPgR(void *p) {
      delete [] ((vector<map<double,CLPBinCont> >*)p);
   }
   static void destruct_vectorlEmaplEdoublecOCLPBinContgRsPgR(void *p) {
      typedef vector<map<double,CLPBinCont> > current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<map<double,CLPBinCont> >

namespace ROOT {
   void vectorlEstringgR_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void vectorlEstringgR_Dictionary();
   static void *new_vectorlEstringgR(void *p = 0);
   static void *newArray_vectorlEstringgR(Long_t size, void *p);
   static void delete_vectorlEstringgR(void *p);
   static void deleteArray_vectorlEstringgR(void *p);
   static void destruct_vectorlEstringgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<string>*)
   {
      vector<string> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<string>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<string>", -2, "prec_stl/vector", 49,
                  typeid(vector<string>), DefineBehavior(ptr, ptr),
                  0, &vectorlEstringgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<string>) );
      instance.SetNew(&new_vectorlEstringgR);
      instance.SetNewArray(&newArray_vectorlEstringgR);
      instance.SetDelete(&delete_vectorlEstringgR);
      instance.SetDeleteArray(&deleteArray_vectorlEstringgR);
      instance.SetDestructor(&destruct_vectorlEstringgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<string> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<string>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEstringgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<string>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEstringgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<string> : new vector<string>;
   }
   static void *newArray_vectorlEstringgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<string>[nElements] : new vector<string>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEstringgR(void *p) {
      delete ((vector<string>*)p);
   }
   static void deleteArray_vectorlEstringgR(void *p) {
      delete [] ((vector<string>*)p);
   }
   static void destruct_vectorlEstringgR(void *p) {
      typedef vector<string> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<string>

/********************************************************
* objects/dict_CLPTemplateMorph.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && (__GNUC__ > 3) && (__GNUC_MINOR__ > 1)
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtabledict_CLPTemplateMorph();

extern "C" void G__set_cpp_environmentdict_CLPTemplateMorph() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("CLPTemplateMorph.h");
  G__cpp_reset_tagtabledict_CLPTemplateMorph();
}
#include <new>
extern "C" int G__cpp_dllrevdict_CLPTemplateMorph() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* CLPTemplateMorph */
static int G__dict_CLPTemplateMorph_484_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CLPTemplateMorph* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CLPTemplateMorph[n];
     } else {
       p = new((void*) gvp) CLPTemplateMorph[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CLPTemplateMorph;
     } else {
       p = new((void*) gvp) CLPTemplateMorph;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CLPTemplateMorph* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new CLPTemplateMorph((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
   } else {
     p = new((void*) gvp) CLPTemplateMorph((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CLPTemplateMorph* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 5
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new CLPTemplateMorph(
(const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Axis_t) G__double(libp->para[3])
, (Axis_t) G__double(libp->para[4]));
   } else {
     p = new((void*) gvp) CLPTemplateMorph(
(const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Axis_t) G__double(libp->para[3])
, (Axis_t) G__double(libp->para[4]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const CLPTemplateMorph*) G__getstructoffset())->size());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const CLPTemplateMorph*) G__getstructoffset())->dontRemovePoints());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTemplateMorph*) G__getstructoffset())->setDontRemovePoints((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const CLPTemplateMorph*) G__getstructoffset())->smoothDeltas());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTemplateMorph*) G__getstructoffset())->setSmoothDeltas((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTemplateMorph*) G__getstructoffset())->setOutputAll((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const CLPTemplateMorph*) G__getstructoffset())->isMorphContainer());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const CLPTemplateMorph*) G__getstructoffset())->noUnderOverflow());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((CLPTemplateMorph*) G__getstructoffset())->setNoUnderOverflow((bool) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((CLPTemplateMorph*) G__getstructoffset())->setNoUnderOverflow();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTemplateMorph*) G__getstructoffset())->addDefaultTemplate((TH1F*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 105, (long) ((CLPTemplateMorph*) G__getstructoffset())->addMorphVariable(*(string*) libp->para[0].ref, (double) G__double(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 105, (long) ((CLPTemplateMorph*) G__getstructoffset())->addMorphVariable(*(string*) libp->para[0].ref));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTemplateMorph*) G__getstructoffset())->addMorphTemplate(*(string*) libp->para[0].ref, (double) G__double(libp->para[1])
, (TH1F*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTemplateMorph*) G__getstructoffset())->addMorphTemplate((int) G__int(libp->para[0]), (double) G__double(libp->para[1])
, (TH1F*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTemplateMorph*) G__getstructoffset())->setParamVec(*(CLPTemplateMorph::DVec*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTemplateMorph*) G__getstructoffset())->setParamVecFromArray((const double*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const CLPTemplateMorph*) G__getstructoffset())->morphIndex(*(string*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTemplateMorph*) G__getstructoffset())->setInternalIndicies(*(CLPTemplateMorph::SVec*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTemplateMorph*) G__getstructoffset())->recalculate();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const CLPTemplateMorph*) G__getstructoffset())->allTGraphs(*(CLPTemplateMorph::TGraphPtrVec*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTemplateMorph*) G__getstructoffset())->addMorph((CLPTemplateMorph*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTemplateMorph*) G__getstructoffset())->addMorph(*(CLPTemplateMorph*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const CLPTemplateMorph*) G__getstructoffset())->th1fCopy());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      CLPTemplateMorph::setParamVecs(*(CLPTemplateMorph::PtrVec*) libp->para[0].ref, *(CLPTemplateMorph::DVec*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) CLPTemplateMorph::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CLPTemplateMorph::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) CLPTemplateMorph::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      CLPTemplateMorph::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLPTemplateMorph*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CLPTemplateMorph::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CLPTemplateMorph::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CLPTemplateMorph::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_CLPTemplateMorph_484_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CLPTemplateMorph::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__dict_CLPTemplateMorph_484_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   CLPTemplateMorph* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new CLPTemplateMorph(*(CLPTemplateMorph*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef CLPTemplateMorph G__TCLPTemplateMorph;
static int G__dict_CLPTemplateMorph_484_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (CLPTemplateMorph*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((CLPTemplateMorph*) (soff+(sizeof(CLPTemplateMorph)*i)))->~G__TCLPTemplateMorph();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (CLPTemplateMorph*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((CLPTemplateMorph*) (soff))->~G__TCLPTemplateMorph();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* CLPTemplateMorph */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncdict_CLPTemplateMorph {
 public:
  G__Sizep2memfuncdict_CLPTemplateMorph(): p(&G__Sizep2memfuncdict_CLPTemplateMorph::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncdict_CLPTemplateMorph::*p)();
};

size_t G__get_sizep2memfuncdict_CLPTemplateMorph()
{
  G__Sizep2memfuncdict_CLPTemplateMorph a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancedict_CLPTemplateMorph() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph))) {
     CLPTemplateMorph *G__Lderived;
     G__Lderived=(CLPTemplateMorph*)0x1000;
     {
       TH1F *G__Lpbase=(TH1F*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph),G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_TH1F),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TH1 *G__Lpbase=(TH1*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph),G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_TH1),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph),G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph),G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TAttLine *G__Lpbase=(TAttLine*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph),G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_TAttLine),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TAttFill *G__Lpbase=(TAttFill*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph),G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_TAttFill),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TAttMarker *G__Lpbase=(TAttMarker*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph),G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_TAttMarker),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TArrayF *G__Lpbase=(TArrayF*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph),G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_TArrayF),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TArray *G__Lpbase=(TArray*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph),G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_TArray),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetabledict_CLPTemplateMorph() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Axis_t",100,-1,0,-1);
   G__setnewtype(-1,"Axis values type (double)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<CLPBin>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlECLPBincOallocatorlECLPBingRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlECLPBincOallocatorlECLPBingRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlECLPBincOallocatorlECLPBingRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlECLPBincOallocatorlECLPBingRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlECLPBincOallocatorlECLPBingRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<double,CLPBinCont>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_maplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<double,CLPBinCont,less<double> >",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_maplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<DMap>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > > >",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("DVec",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("IVec",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEintcOallocatorlEintgRsPgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("SVec",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEstringcOallocatorlEstringgRsPgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGraph*>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlETGraphmUcOallocatorlETGraphmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlETGraphmUcOallocatorlETGraphmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlETGraphmUcOallocatorlETGraphmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlETGraphmUcOallocatorlETGraphmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlETGraphmUcOallocatorlETGraphmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TGraphPtrVec",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlETGraphmUcOallocatorlETGraphmUgRsPgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<CLPTemplateMorph*>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlECLPTemplateMorphmUcOallocatorlECLPTemplateMorphmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlECLPTemplateMorphmUcOallocatorlECLPTemplateMorphmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlECLPTemplateMorphmUcOallocatorlECLPTemplateMorphmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlECLPTemplateMorphmUcOallocatorlECLPTemplateMorphmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlECLPTemplateMorphmUcOallocatorlECLPTemplateMorphmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("PtrVec",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlECLPTemplateMorphmUcOallocatorlECLPTemplateMorphmUgRsPgR),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("DVecConstIter",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEdoublecOallocatorlEdoublegRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("IVecIter",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEintcOallocatorlEintgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("IVecConstIter",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEintcOallocatorlEintgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("SVecConstIter",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TGraphPtrVecConstIter",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlETGraphmUcOallocatorlETGraphmUgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("PtrVecIter",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlECLPTemplateMorphmUcOallocatorlECLPTemplateMorphmUgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("PtrVecConstIter",117,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlECLPTemplateMorphmUcOallocatorlECLPTemplateMorphmUgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* CLPTemplateMorph */
static void G__setup_memvarCLPTemplateMorph(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph));
   { CLPTemplateMorph *p; p=(CLPTemplateMorph*)0x1000; if (p) { }
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_dontRemovePoints=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_smoothDeltas=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_outputAll=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_isMorphContainer=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_noUnderOverflow=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("DVec"),-1,4,"m_paramVec=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("DVec"),-1,4,"m_centerVec=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("SVec"),-1,4,"m_nameVec=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("IVec"),-1,4,"m_indexVec=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlECLPTemplateMorphmUcOallocatorlECLPTemplateMorphmUgRsPgR),G__defined_typename("PtrVec"),-1,4,"m_ptrVec=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPBinCont),-1,-1,4,"m_defaultBC=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgR),G__defined_typename("DMapVec"),-1,4,"m_deltaMorphMapVec=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvardict_CLPTemplateMorph() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncCLPTemplateMorph(void) {
   /* CLPTemplateMorph */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph));
   G__memfunc_setup("CLPTemplateMorph",1569,G__dict_CLPTemplateMorph_484_0_1, 105, G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CLPTemplateMorph",1569,G__dict_CLPTemplateMorph_484_0_2, 105, G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph), -1, 0, 2, 1, 1, 0, 
"C - - 10 - name C - - 10 - title", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CLPTemplateMorph",1569,G__dict_CLPTemplateMorph_484_0_3, 105, G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph), -1, 0, 5, 1, 1, 0, 
"C - - 10 - name C - - 10 - title "
"i - 'Int_t' 0 - numBins d - 'Axis_t' 0 - xlow "
"d - 'Axis_t' 0 - xhigh", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("size",443,G__dict_CLPTemplateMorph_484_0_4, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("dontRemovePoints",1696,G__dict_CLPTemplateMorph_484_0_5, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setDontRemovePoints",1996,G__dict_CLPTemplateMorph_484_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - dontRemovePoints", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("smoothDeltas",1271,G__dict_CLPTemplateMorph_484_0_7, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setSmoothDeltas",1571,G__dict_CLPTemplateMorph_484_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - smoothDeltas", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setOutputAll",1270,G__dict_CLPTemplateMorph_484_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - outputAll", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("isMorphContainer",1669,G__dict_CLPTemplateMorph_484_0_10, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("noUnderOverflow",1583,G__dict_CLPTemplateMorph_484_0_11, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setNoUnderOverflow",1883,G__dict_CLPTemplateMorph_484_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'true' noUnderOverflow", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addDefaultTemplate",1834,G__dict_CLPTemplateMorph_484_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TH1F' - 0 - histPtr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addMorphVariable",1621,G__dict_CLPTemplateMorph_484_0_14, 105, -1, -1, 0, 2, 1, 1, 0, 
"u 'string' - 11 - name d - - 0 '0.' center", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addMorphTemplate",1643,G__dict_CLPTemplateMorph_484_0_15, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'string' - 11 - name d - - 0 - value "
"U 'TH1F' - 0 - histPtr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addMorphTemplate",1643,G__dict_CLPTemplateMorph_484_0_16, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - index d - - 0 - value "
"U 'TH1F' - 0 - histPtr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setParamVec",1115,G__dict_CLPTemplateMorph_484_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'CLPTemplateMorph::DVec' 11 - paramVec", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setParamVecFromArray",2030,G__dict_CLPTemplateMorph_484_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "D - - 10 - arrayPtr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("morphIndex",1054,G__dict_CLPTemplateMorph_484_0_19, 105, -1, -1, 0, 1, 1, 1, 8, "u 'string' - 11 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setInternalIndicies",1969,G__dict_CLPTemplateMorph_484_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<string,allocator<string> >' 'CLPTemplateMorph::SVec' 11 - nameVec", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("recalculate",1157,G__dict_CLPTemplateMorph_484_0_21, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("allTGraphs",1010,G__dict_CLPTemplateMorph_484_0_22, 121, -1, -1, 0, 1, 1, 1, 8, "u 'vector<TGraph*,allocator<TGraph*> >' 'CLPTemplateMorph::TGraphPtrVec' 1 - tgraphPtrVec", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addMorph",815,G__dict_CLPTemplateMorph_484_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "U 'CLPTemplateMorph' - 0 - morphPtr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addMorph",815,G__dict_CLPTemplateMorph_484_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "u 'CLPTemplateMorph' - 1 - morph", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("th1fCopy",782,G__dict_CLPTemplateMorph_484_0_25, 85, G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_TH1F), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setParamVecs",1230,G__dict_CLPTemplateMorph_484_0_26, 121, -1, -1, 0, 2, 3, 1, 0, 
"u 'vector<CLPTemplateMorph*,allocator<CLPTemplateMorph*> >' 'CLPTemplateMorph::PtrVec' 1 - morphPtrVec u 'vector<double,allocator<double> >' 'CLPTemplateMorph::DVec' 11 - paramVec", (char*)NULL, (void*) (void (*)(CLPTemplateMorph::PtrVec&, const CLPTemplateMorph::DVec&))(&CLPTemplateMorph::setParamVecs), 0);
   G__memfunc_setup("_printTGraph",1234,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 8, "u 'CLPBinCont' - 11 - cont", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("_fillMorphContainer",1967,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__dict_CLPTemplateMorph_484_0_29, 85, G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (TClass* (*)())(&CLPTemplateMorph::Class), 0);
   G__memfunc_setup("Class_Name",982,G__dict_CLPTemplateMorph_484_0_30, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&CLPTemplateMorph::Class_Name), 0);
   G__memfunc_setup("Class_Version",1339,G__dict_CLPTemplateMorph_484_0_31, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (Version_t (*)())(&CLPTemplateMorph::Class_Version), 0);
   G__memfunc_setup("Dictionary",1046,G__dict_CLPTemplateMorph_484_0_32, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (void (*)())(&CLPTemplateMorph::Dictionary), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__dict_CLPTemplateMorph_484_0_36, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__dict_CLPTemplateMorph_484_0_37, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&CLPTemplateMorph::DeclFileName), 0);
   G__memfunc_setup("ImplFileLine",1178,G__dict_CLPTemplateMorph_484_0_38, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&CLPTemplateMorph::ImplFileLine), 0);
   G__memfunc_setup("ImplFileName",1171,G__dict_CLPTemplateMorph_484_0_39, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&CLPTemplateMorph::ImplFileName), 0);
   G__memfunc_setup("DeclFileLine",1152,G__dict_CLPTemplateMorph_484_0_40, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&CLPTemplateMorph::DeclFileLine), 0);
   // automatic copy constructor
   G__memfunc_setup("CLPTemplateMorph", 1569, G__dict_CLPTemplateMorph_484_0_41, (int) ('i'), G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph), -1, 0, 1, 1, 1, 0, "u 'CLPTemplateMorph' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~CLPTemplateMorph", 1695, G__dict_CLPTemplateMorph_484_0_42, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncdict_CLPTemplateMorph() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaldict_CLPTemplateMorph() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcdict_CLPTemplateMorph() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__dict_CLPTemplateMorphLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_vectorlEdoublecOallocatorlEdoublegRsPgRcLcLiterator = { "vector<double,allocator<double> >::iterator" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_TArray = { "TArray" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_TAttLine = { "TAttLine" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_TAttFill = { "TAttFill" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_TAttMarker = { "TAttMarker" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_TArrayF = { "TArrayF" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_TH1 = { "TH1" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_TH1F = { "TH1F" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_vectorlECLPBincOallocatorlECLPBingRsPgR = { "vector<CLPBin,allocator<CLPBin> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlECLPBincOallocatorlECLPBingRsPgRcLcLiteratorgR = { "reverse_iterator<vector<CLPBin,allocator<CLPBin> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_CLPBinCont = { "CLPBinCont" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_maplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgR = { "map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > >" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgR = { "vector<map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > >,allocator<map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > > > >" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > >,allocator<map<double,CLPBinCont,less<double>,allocator<pair<const double,CLPBinCont> > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_CLPTemplateMorph = { "CLPTemplateMorph" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_vectorlEintcOallocatorlEintgRsPgRcLcLiterator = { "vector<int,allocator<int> >::iterator" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator = { "vector<string,allocator<string> >::iterator" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_vectorlETGraphmUcOallocatorlETGraphmUgRsPgR = { "vector<TGraph*,allocator<TGraph*> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_vectorlETGraphmUcOallocatorlETGraphmUgRsPgRcLcLiterator = { "vector<TGraph*,allocator<TGraph*> >::iterator" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlETGraphmUcOallocatorlETGraphmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TGraph*,allocator<TGraph*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_vectorlECLPTemplateMorphmUcOallocatorlECLPTemplateMorphmUgRsPgR = { "vector<CLPTemplateMorph*,allocator<CLPTemplateMorph*> >" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_vectorlECLPTemplateMorphmUcOallocatorlECLPTemplateMorphmUgRsPgRcLcLiterator = { "vector<CLPTemplateMorph*,allocator<CLPTemplateMorph*> >::iterator" , 99 , -1 };
G__linked_taginfo G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlECLPTemplateMorphmUcOallocatorlECLPTemplateMorphmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<CLPTemplateMorph*,allocator<CLPTemplateMorph*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtabledict_CLPTemplateMorph() {
  G__dict_CLPTemplateMorphLN_TClass.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_TBuffer.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_TMemberInspector.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_TObject.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_TNamed.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_vectorlEdoublecOallocatorlEdoublegRsPgRcLcLiterator.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_string.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_TArray.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_TAttLine.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_TAttFill.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_TAttMarker.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_TArrayF.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_TH1.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_TH1F.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_vectorlECLPBincOallocatorlECLPBingRsPgR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlECLPBincOallocatorlECLPBingRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_CLPBinCont.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_maplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_CLPTemplateMorph.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_vectorlEintcOallocatorlEintgRsPgRcLcLiterator.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_vectorlETGraphmUcOallocatorlETGraphmUgRsPgR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_vectorlETGraphmUcOallocatorlETGraphmUgRsPgRcLcLiterator.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlETGraphmUcOallocatorlETGraphmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_vectorlECLPTemplateMorphmUcOallocatorlECLPTemplateMorphmUgRsPgR.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_vectorlECLPTemplateMorphmUcOallocatorlECLPTemplateMorphmUgRsPgRcLcLiterator.tagnum = -1 ;
  G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlECLPTemplateMorphmUcOallocatorlECLPTemplateMorphmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtabledict_CLPTemplateMorph() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_TClass);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_TObject);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_TNamed);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_vectorlEdoublecOallocatorlEdoublegRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_string);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_TArray);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_TAttLine);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_TAttFill);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_TAttMarker);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_TArrayF);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_TH1);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_TH1F);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_vectorlECLPBincOallocatorlECLPBingRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlECLPBincOallocatorlECLPBingRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_CLPBinCont);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_maplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_vectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRcOallocatorlEmaplEdoublecOCLPBinContcOlesslEdoublegRcOallocatorlEpairlEconstsPdoublecOCLPBinContgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__dict_CLPTemplateMorphLN_CLPTemplateMorph),sizeof(CLPTemplateMorph),-1,61696,"CLPTemplateMorph Class",G__setup_memvarCLPTemplateMorph,G__setup_memfuncCLPTemplateMorph);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_vectorlEintcOallocatorlEintgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_vectorlETGraphmUcOallocatorlETGraphmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_vectorlETGraphmUcOallocatorlETGraphmUgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlETGraphmUcOallocatorlETGraphmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_vectorlECLPTemplateMorphmUcOallocatorlECLPTemplateMorphmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_vectorlECLPTemplateMorphmUcOallocatorlECLPTemplateMorphmUgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G__dict_CLPTemplateMorphLN_reverse_iteratorlEvectorlECLPTemplateMorphmUcOallocatorlECLPTemplateMorphmUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupdict_CLPTemplateMorph(void) {
  G__check_setup_version(30051515,"G__cpp_setupdict_CLPTemplateMorph()");
  G__set_cpp_environmentdict_CLPTemplateMorph();
  G__cpp_setup_tagtabledict_CLPTemplateMorph();

  G__cpp_setup_inheritancedict_CLPTemplateMorph();

  G__cpp_setup_typetabledict_CLPTemplateMorph();

  G__cpp_setup_memvardict_CLPTemplateMorph();

  G__cpp_setup_memfuncdict_CLPTemplateMorph();
  G__cpp_setup_globaldict_CLPTemplateMorph();
  G__cpp_setup_funcdict_CLPTemplateMorph();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncdict_CLPTemplateMorph();
  return;
}
class G__cpp_setup_initdict_CLPTemplateMorph {
  public:
    G__cpp_setup_initdict_CLPTemplateMorph() { G__add_setup_func("dict_CLPTemplateMorph",(G__incsetup)(&G__cpp_setupdict_CLPTemplateMorph)); G__call_setup_funcs(); }
   ~G__cpp_setup_initdict_CLPTemplateMorph() { G__remove_setup_func("dict_CLPTemplateMorph"); }
};
G__cpp_setup_initdict_CLPTemplateMorph G__cpp_setup_initializerdict_CLPTemplateMorph;

